In [1]:
import pickle
import os
import numpy as np
import pandas as pd

from contextualized_topic_models.utils.data_preparation import TopicModelDataPreparation
from contextualized_topic_models.models.ctm import CombinedTM
from sentence_transformers import SentenceTransformer

In [9]:
########## TEST ############
df = pd.read_csv("../data/preprocessed/reviews_trust_clean.csv")

qualite_keywords = [
    r"cass(é|ée|és|ées)?",
    r"casse(r)?",
    r"d[ée]f(ec|aut)(s)?",
    r"qualit(é|e|és|es|ées|ees)?",
    r"mati[èe]re(s)?",
    r"soli(de|d|de)?",
    r"résistan(t|ce|ces|t)?",
    r"correspond(ait|s|t)?",
    r"fonctionne(r)?",
    r"d[ée]f(ec)?tueu(se|s|e|x|ses)?",
    r"tiss(u|us|u)?(x)?",
    r"couleur(s|e)?",
    r"((trop|un peu|très)\s+petit(e|es)?|taille(nt)?\s+(trop|un peu|très)?\s*petit(e|es)?)"
    r"grand(e|es|s)?",
    r"ray(é|ee|ée|e|és|és|ees|ée|ure|ures)",
    r"finitions?",
    r"beau(x)?",
    r"belle(s)?",
    r"joli(e|es|s)?",
    r"conforme(s)?",
    r"en panne(s)?",
    r"bas de gamme",
    r"inutilisable(s)?",
]


livraison_keywords = [
    r"livr(é|er|aison|aisons|ées|ée|eur)?",
    r"passage(s)?",
    r"coli(s)?",
    r"paquet(s)?",
    r"carton(s)?",
    r"retard(é|ée|s)?",
    r"dpd",
    r"gls",
    r"poste",
    r"facteur(s)?",
    r"mondial relay",
    r"mondial relais",
    r"relais",
    r"relay",
    r"point relais",
    r"domicile",
    r"retrait",
    r"bureau de poste",
    r"ouvert(s|e|es)?",
    r"endommag(é|ée|és|ées)?",
    r"déposé(e|s)?",
    r"laisser?|laissé(e|s)?",
    r"transporteur(s)?",
    r"manquant(e|s)?",
    r"incomplet(s|es)?",
    r"abîmé(e|s)?",
    r"déchiré(e|s)?",
]

client_keywords = [
    r"service client(s)?",
    r"\bsav\b",
    r"service après vente",
    r"répond(re|s|u)?",
    r"réponse(s)?",
    r"rembour(s|ser|sement|sez)?",
    r"contact(er|e|es)?",
    r"mail(s)?|email(s)?",
    r"appel(er|s)?",
    r"incompétent(e|s|es)?",
    r"incompétence",
    r"escroc(s)?",
    r"arnaque(s)?",
    r"voleur(s|ses)?",
    r"solution(s)?",
    r"aucune réponse",
    r"réclamation(s)?",
    r"annul(é|ée|er|ation|ations)",
    r"litige(s)?",
]

def make_regex(words):
    return r"\b(" + "|".join(words) + r")\b"

df["Qualite_Produit"] = df["clean_comment"].str.contains(make_regex(qualite_keywords), case=False, na=False).astype(int)
df["Service_Livraison"] = df["clean_comment"].str.contains(make_regex(livraison_keywords), case=False, na=False).astype(int)
df["Service_Client"] = df["clean_comment"].str.contains(make_regex(client_keywords), case=False, na=False).astype(int)

df[["Qualite_Produit", "Service_Livraison", "Service_Client"]].sum()

df_annotated = df[
    (df["Qualite_Produit"] == 1)
    | (df["Service_Livraison"] == 1)
    | (df["Service_Client"] == 1)
]

#pour afficher le nombre d'avis qui ont au moins 1 label
df_annotated.shape[0]

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

df_sample = df_annotated[["clean_comment", "Qualite_Produit", "Service_Livraison", "Service_Client"]].head(100)
df_sample

C:\Users\georg\AppData\Local\Temp\ipykernel_25900\2518547857.py:86: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["Qualite_Produit"] = df["clean_comment"].str.contains(make_regex(qualite_keywords), case=False, na=False).astype(int)
C:\Users\georg\AppData\Local\Temp\ipykernel_25900\2518547857.py:87: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["Service_Livraison"] = df["clean_comment"].str.contains(make_regex(livraison_keywords), case=False, na=False).astype(int)
C:\Users\georg\AppData\Local\Temp\ipykernel_25900\2518547857.py:88: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["Service_Client"] = df["clean_comment"].str.contains(make_regex(client_keywords), case=False, na=False).astype(int)

,clean_comment,Qualite_Produit,Service_Livraison,Service_Client
0,"bonjour , ca doit faire 5 ans environ que je suis membre showrooprive . je n ’ ai jamais eu de soucis en particulier à part 2/3 petites bricoles…par contre depuis ces 3 derniers mois , une vraie catastrophe ! j ’ ai eu 3 commandes annulées d ’ affiliés… à se demander si les ventes sont bien réelles histoires de nous faire payer et que showroom « joue » avec notre argent en se faisant des intérêts bancaires sur notre dos ! ! ! ! la 1 ère commande « machines et cafés » 89,99€… annulé 1 mois après …la 2e commande « don ’ t call me jennifer » 65,16€… annulé 1 mois après …la 3e commande « techwood » 46,29€… annulé 1 mois après….je l ’ apprends toujours par mail…le même message « bateau » « malgré tous les efforts… .. bla-bla-bla bien évidemment , pas de dédommagement ! ! ! ! ben . non , hein , pourquoi faire ? ! ? ! je doute que ce site soit aussi fiable et sérieux qu ’ au début ! au final je vais juste rester fidèle sur n autre site marchand ! ! ! ! ! très décevant … plus du tout confiance je ne recommande plus du tout ce site et j ’ en fais part à mon entourage et réseaux sociaux ! ! afin d ’ éviter que d ’ autres personnes connaissent ce même type d ’ expérience ! !",0,0,1
1,vente lacoste article manquant photo prise sur 6 articles la moitié livrée sans explication manque de respect.numero de commande 230130353,0,1,0
2,"vente lacoste honteuse , article erroné , article manquant , pas de bon de livraison , retard et service client désastreux.après deux appels désastreux , je tenais à avertir les plus courageux qui oseront commander et contacter ce service client . showroom fait dans le pire du pire . attentions aux oreilles , votre interlocuteur vous parle dans environnement très bruyant de type chantier , coup de marteaux et jet de matériaux à proximité du micro . vous demandez de faire cesser la nuisance , on vous répond que non car ils vous entendent très bien . erreur sur votre commande , l ’ interlocuteur ne vous crois pas , il faut envoyer les captures d ’ écran de sa commande pour les convaincre qu ’ ils font bien n ’ importe quoi.la commande arrive en plusieurs fois pour une même vente , retard , article manquant et pas de bon livraison pour comprendre quoi que ce soit , on ne sait rien et il est impossible d ’ obtenir le suivi de livraison et les détails pour les articles manquants.un article annulé par showroom car n ’ était plus en stock mais toujours proposé à la vente . ( commande n°230077467 et commande n•230077467 ) ca fait beaucoup d ’ un coup , c ’ est inadmissible.fuyez !",0,1,1
4,commande téléphone etat a+ . livraison d un vieux téléphone pourri sans batterie rayé partout et inaudible ! ! ! super l affaire 300 euros a la poubelle merci showroomprivee ! ! ! passez votre chemin ils sont nuls et ne contrôlent même pas ce qu ils proposent a la vente .,1,1,0
5,"commande passée pour une vente lacoste , livraison 15 nous après la date prévue , déjà 6 semaines après l'achat , sur 3 produits , 2 manquants . pas pro , pas sérieux , aucun geste commercial hormis le remboursement promis des 2 articles manquants .",0,1,1
6,annulation de commande après 2 mois d ’ attente dans un geste et sans explication . retard de livraison et report à 3 reprise pour se résultat incompréhensible et inadmissible je recommande pas le site mieux vaut aller sur vente privée au mon d on attend mais on a sa commande,0,1,1
7,"extrêmement déçue de la vente apple ! ! achat d ’ un iphone reconditionné grade a+ ( fournisseur prs , phone recycle ) il a fonctionné 15 jours ! ! ! sav lamentable jusqu ’ a 6 jours pour répondre à une ’ question et pas de prise en charge des frais de retour pour réparation ... sav showroom qui lit les mails ’ en diagonale et répond à côté ! lamentable ... téléphone pas encore récupéré , ce sera mon dernier achat ! !",0,0,1
9,s'il y'avait une option : ne pas mettre d'étoile ( une étoile c'est trop ! ) je serais contente . j'ai passé une commande mi-avril et là nous sommes en mi-juin je ne l'ai toujours pas reçu ! et quand je leur faire part de ça il ne me réponde pas ! j'ai commandé des articles de jennyfer via leur site . c'est marqué colis expédié via mondial relay mais depuis plus rien même pas un numéro de suivi !,0,1,0
10,"arnaque j ’ ai acheté une combinaison blanche à 33€ au lieu de soit disant 100€ , que j ’ ai reçu + d ’ un mois après , avec des traces noires sur le bas de la combi et surtout elle était super transparente ! bref impossible à mettre même avec des sous vêtements couleur chair ! grosse arnaque c ’ est inadmissible je vais la renvoyer avec 6,50€ de frais à mes charges ! en espérant être remboursée ! je ne vous conseille pas du tout showroom privé",1,0,1
11,"bonjour , commande fait sur showroom n° 233332467 avec un point relais défini . cette commande a été déviée de son point d'origine de plus de 6km par le bon vouloir du transporteur ? ? réponse de showroom n'allez pas le chercher et on vous remboursera ? ? quelle est l'interré de commander d'attendre plus d'un mois pour le remboursement . sur amazon l'ecoute et le respect du client est leur priorité.merci de prendre exemple",0,1,1
12,"pour commander il n ' y a pas de problème mais pour les retours c'est très compliqué , l'article étant défectueux.les conseillers n'écoutent pas et répétent toujours pareils . je suis très déçue et hésiterais désormais à commander par ce site.surtout que j'attends aussi ma commande lacoste , qui était prévue pour la fête des pères et qui est encore repoussée . commande passée le 5 mai 2021je trouve que c'est un peu exagéré comme délai .",1,0,0
13,"2 robes achetées sur showroom privées , une pour ma fille , une pour moi . ma fille me dit qu'il y a un trou , donc je regarde du coup les deux robes : toutes les deux défectueuses ( trou au niveau de la couture de l'une , et une maille sortie dans l'autre ) . je retourne donc le colis en prenant la peine de mettre des post it là où les robes sont abimées . je renvoie le colis avec le retour gratuit . plusieurs jours après , je reçois un mail de showroom me disant que mon remboursement a été effectué . sauf que , ils m'ont enlevé 6.50€ de frais de retour ! ! ! ! ! inadmissible , ce n'est pas a moi de payer pour leurs robes défectueuses . et impossible de faire une réclamation sur le service client , depuis 24h , un message d'erreur m'empêche de la faire . mais comme par hasard , quand je valide ma réclamation , ça ne marche pas ! je ne lâche rien , je veux être remboursée et j'ai pris des photos .",1,1,1
14,"ce sont des voleurs . showroomprivé vend des ipad reconditionnés en mauvais état . ils rejettent la faute sur leurs fournisseurs mais vous laisse vous démerder avec eux . soit disant ils doivent appeler mais j'attends toujours depuis janvier . sara du service client ne comprends pas mon explication . pour tout renseignement voici mon numéro 06 27 27 23 84 . avec veepee , il n ' y a pas de problèmes , ils sont sérieux .",0,1,1
15,une bande d ’ incapable qui ne savent pas expédier des colis et quand vous avez le malheur de leur demander de vous le faire parvenir c ’ est pas possible on vous rembourse . tout ça sans excuses ni geste commercial . la satisfaction client chez eux c ’ est pas une priorité .,0,1,0
16,"achete une pergola sur shorom vendu par sourcidys a tours paye 37 € de frais de livraison .il y avait 3 colis j en ai reçu 2 , il me manque le 3 ème qui contient les pieds .. depuis le 10 juin pas de nouvelles , la société ne répond pas ... ni a moi ni a shorom .du coup impossible de la monter paye 299 euros pour rien ..... site à banir.shorom a de suite pris la réclamation en compte mais rien bouge .",0,1,1
17,"mon colis est arriver abimé , meuble hannah home finition bas de gamme , très déçu.envie de renvoyer le colis , demande de retour demander le 2 juin 2021 et voila j'attend toujours l'étiquettes de retour service client par téléphone non efficace , ils sont la juste pour répondre aux appels , donc problème non résolue ce jour.je laisserais un avis favorable au retour de showroomprive",1,1,1
18,à fuir showroomprive en cas de problème service client déplorable nul et j'en passe j'ai passé une commande le 5 mai 2021 sur une vente lacoste je reçois un mail m'informant que la livraison va être retardé au plus tard au 11 juin or à ce jour je reçois mon colis avec 2 articles manquants à ma commande ! ! ! comment numéro 23 01 12229 vente lacoste ! ! ! j'ai passé cette commande dans l'espoir de l'offrir pour la fête des pères qui arrive ce dimanche et à ce jour je me retrouve avec une commande incomplète aucune information sur le reste de ma commande showroom me répond d'attendre mdr ils sont malins cela et culotté ! ! ! ce n'est pas la première fois que je rencontre des problèmes avec les colis franchement je déconseille vivement maintenant d'acheter sur showroomprive commande qui n'arrive pas commande incomplète et je ne vous explique pas le casse-tête pour être remboursé ! ! ! en tout cas je ne serai plus cliente chez eux attention à vous futur acheteur je vous aurai prévenu des incompétence de showroomprive ! ! ! nous sommes aujourd'hui le 17 juin et je n'aurais certainement pas le reste de ma commande pour dimanche des images même pas les clients et ne sais même pas répondre où est le reste de ma commande ! ! ! ils font des ventes et ne savent pas assumer et ne savent même pas répondre à leurs clients ! ! ! alors merci de me rembourser au plus vite ou de m'envoyer ma commande dès aujourd'hui cher service client showroomprive à vous de faire vos preuves car vu les commentaires négatifs je pense que vous allez perdre pas mal de clients😉,1,1,1
19,"j'ai fait la commande d'une sacoche et d'un pull lacoste , il y a de ça 1 mois et demi , déjà le temps d'attente est énorme , mais en sois ce n'est pas si grave.par contre sur mon colis à 120 euros , je n'ai reçu qu'un article sur les deux , j'ai envoyé un mail hier et je n'ai toujours pas de réponse .",0,1,1
20,"ne répondent pas aux mails de réclamation malgré relance.suite au message sur truspilot me laissent un message , toujours sur truspilot , m'indiquant qu'ils vont me contacter ... j'attends encore ... j'ai à nouveau relancé par mail et par téléphone et je suis supposée avoir reçu un mail le 15 juin dernier . rien dans ma boîte de réception , rien en spam ... bonnes gens , fuyez !",0,0,1
21,"le service client est expéditif et de mauvaise qualité , après avoir telephoné pour connaitre la procédure de renvoi personne ne m ' a pas informé correctement et après une erreur ils ont refusé de me remboursé de mon article.a fuir , que des problemes chez eux .",1,0,1
22,"showroom s'est trompé dans l'envoi de ma commande pour une montre.je n'ai pas reçu l'article commandé.mais pour le retour , je dois payer l'affranchissement l'erreur est de leur côté . le retour devrait être gratuitencore un plan malhonnête.cette enseigne vend de vraies marques ( le nettoyeur vapeur polti que j'ai vu dans le commerce , et sur le site polti ) . mais l'emballage laissait à désirer . colissimo a tout renforcé , avec l'adhésif a leur nom.etelle vend des articles avec des marques qui ont existées autrefois , mais qui ont arrêté leurs commerces . les chinois rachètent ces marques . et les chinois créent également des marques avec des noms européens pour que cela sonne bien.les montres ne correspondent pas aux prix d'origine soi-disant affichés . de ce fait les soldes semblent tres intéressantes . une montre a 1000 euros , soldées 100 e , cela vous semble-t-il possible ? ce n'est pas ce type de montres que j'ai acheté . il y a également des articles qui ne correspondent pas exactement aux photos , comme des bagues , ou sacs avec des marques et des soldes qui semblent douteuses . c'est de la camelote de mauvaise qualité . donc , ayoub , c'est inutile de faire une réponse de la part de showroom sur le site de trust pilote . je suis directement en contact avec euxmais au vu de vos réponses , toujours les mêmes je me demande si vous existez vraiment ou si vous êtes un robot .",1,0,1
23,"un service clients épouvantable et malhonnête . j ’ ai refusé un colis déchiré et contenant des tasses cassées , et showroomprivé refuse de me rembourser car le transporteur a noté le colis comme livré . ils m ’ ont fait croire à une enquête auprès du transporteur qui aurait duré 15 jours selon eux , pour finalement me répondre « votre colis vous a été livré » . je viens de leur écrire car les téléphonistes sont lamentables , mais je ne me fais pas d ’ illusions . pour moi showroomprivé c ’ est terminé , et pourtant j ’ ai beaucoup acheté sur ce site et depuis des années . je n ’ accepte pas de me faire voler comme ça .",1,1,1
24,"j'ai toujours été cliente chez showroom , jamais déçue . il y a quelques jours , je reçois un article non conforme . on m'envoie le bon retour . je dois faire l'avance des frais , hors de question , on me dit m'envoyer un bon chronopost que j'ai juste à mettre le colis dans ma boîte aux lettres . sauf que je ne reçois pas le bon et rebelote . il y a soit disant un problème avec les bons retour . bref , tant pis , je vais revendre l'article certainement plus cher que celui que je viens de recevoir . hyper déçue 🤬🤬🤬",1,1,0
25,"très déçue ! j ’ ai souvent commandé sur showroom privé , toujours livrée rapidement.je commande un maillot de bain le 23/05 , je reçois un message m ’ informant d ’ un retard de livraison - maintenant annoncée le 21/06 ... jour de mon départ en vacances ... aucun numéro de suivi mondial relay donc impossible de savoir où est mon colis ... commande 231658244",0,1,0
26,"ce site propose beaucoup d ’ articles à des prix très intéressants mais le pb c ’ est que 2 commandes sur 3 n ’ arrivent jamais ( rupture de stock , colis perdu ou endommagé etc… ) . c ’ est vrai que vous ne perdez pas d ’ argent car ils remboursent mais vous n ’ avez pas vos produits.site à éviter fortement… .. ! ! ! !",0,1,0
27,"voleur , escroc ! ! ! ! ! très mauvaise expériencelivraison reçu à moitié après avoir contacté le service client aucune réponse ... aucun dédommagement ! dédouanement en rejettant la faute sur le fournisseur qui est injoignable ! ! un scandale ! a fuir ! ! !",0,0,1
28,tres mauvais service de retour . deux semaines pour réceptionner un retour en plus payante et plus cher que les frais de livraison qu on paye initialement . plus jamais j achete sur showroom .,0,1,0
29,ça fait un mois que ma commande aurait du être livré et showroom fait traîner l ’ affaire malgré mes appels et messages pourtant chronopost m ’ a indiqué le colis comme perdu,0,1,1
30,"cliente depuis des années , déception totale . j ai reçu un colis endommagé , il manquait un produit ( petite valeur ) 3 semaines d'investigation obligatoires , je reçois un mail me disant que la commande était bien livrée mauvaise réponse de leur part . je quitte leur fichier client . de plus les retours sont payants .",0,1,1
31,"sur 5 commandes , 3 ont été partiellement livrées . certes , on reçoit un remboursement des produits non livrés mais qu'en est-il 1 ) des frais de livraison qui devraient être réduits ( ou plutôt annulés complétement en geste commercial ) . 2 ) est-il normal quand on valide une commande que l'on ne puisse avoir les produits à cette époque où l'on connait le stock à tout instant ( en plus , cela fait plusieurs fois pour ricard que le produit que je souhaitais surtout , n'est plus disponible après la commande . 3 ) comme dans de plus en plus de site , il est bien compliqué pour faire part de telle situation et avoir une réponse",0,1,1
32,"dernièrement j'ai publié un avis mentionnant ma mauvaise expérience lors de l'achat d'un lot de boxers fila.après plusieurs échanges avec showroomprive , le services clients a finalement accepté que je retourne les articles . leur analyse a abouti à la décision de me rembourser.bravo showroomprive pour avoir accepté de revoir votre position .",0,0,1
33,"plus jamais ! des escrocs , voleurs avec des qualités de produits minables .",1,0,1
34,"mêmes horribles expériences que beaucoup d ’ autres personnes ici apparemment . j ’ étais très bonne cliente de showroom car les marques et les prix proposés étaient intéressants . mais une énorme détérioration des services s ’ est fait sentir depuis quelques temps . plus moyen de recevoir une seule commande conforme . toujours des erreurs d ’ articles ( je commande une jupe , je reçois des chaussures hommes ... ) , des commandes perdues dans la nature , ou incomplètes sans la moindre explication . si on ne fait pas des pieds et des mains auprès du service client ( qui répond des semaines plus tard ) , les retours sont aux frais du client ce qui est tout bonnement inacceptable . résultat , j ’ adorais showroomprive , mais maintenant , au bout d ’ une dizaine de commandes défectueuses j ’ en ai assez de perdre mon temps et mon argent , je commande à la concurrence avec qui il n ’ y a jamais aucun souci . showroomprive mène une politique idiote . le client est vraiment pris pour une vache à lait , seulement bon à donner des sous , sans que l ’ on se soucie de sa satisfaction . service client quasi inexistant , aucunement à l ’ écoute . a la limite de l ’ arnaque . je ne comprends pas que le site ne soit pas encore fermé ... a s ’ entêter dans cette voie , showroom est en train de perdre tous ses clients ...",1,0,1
35,"bonjour , j'ai réservé un voyage pour l'egypte sur le site de showroom . ils ont bien débités l'argent . la 1er fois le voyage a été annulé par l'opérateur travel evasion d'après eux , j'ai du reporter mes vacances . la 2eme de nouveau annuler , avec aucunes explications ni par phone , ni par mail . mon départ était prévu pour le 19 juin 2021 , j'apprends avant - 10 jours que mon voyage est encore annulé , je ne comprends pas pourquoi étant donné que l'egypte est ouvert aux touristiques . travaillant à l'aéroport plusieurs personnes s ' y rendent . attention , je vous conseille de faire attention avec ce site , ils travaillent avec notre argent pendant ce temps . vous appelez le site et malheureusement les personnes aux bouts du fils ne sont pas en mesure de vous répondre , de plus personne ne vous rappel également .",0,1,1
36,"j'ai passé une commande fin de janvier et je l'ai reçue en février , c'est une montre à vente ourlet , mais je me suis surprise qu'il y a un défaut invisible c'est le dysfonctionnement du fermoir , et quand j'ai essayé de contacter le fournisseur , son adresse mail est introuvable par contre j'ai envoyé pas mal des mails à showroomprivée pour me renseigner , sur le service après vente car j'ai une garantie de 24 mois , et la meilleure c'est qu'on m ' a dit que la garantie ne couvre pas le fermoir de la montre et qui sont navrés que le fermoir de la montre est cassé mais non ! excusez-moi ! c'est un défaut qui est venu avec la montre , le fermoir ne tient pas ! j'ai pris en photo la montre qui est toujours neuve mais on m ' a pas encore réponduvraiment à éviter ! c'est la première et la dernière fois que j'achète chez eux je suis vraiment déçue",1,0,1
37,"jusqu ' à présent , j'étais très satisfaite de showroomprive . les commandes étaient conformes et lorsqu'il y a eu des soucis ( oui c'est arrivé : mauvaise pointure , flacon ouvert et déversé dans le colis ... ) , le service client a toujours fait au mieux . je vis en martinique et il est l'un des rares sites à nous livrer . certes , la livraison était plus coûteuse mais cela restait raisonnable . seulement depuis qq temps , cela s'est détérioré . les frais de livraison ont commencé par augmenter de façon surréaliste . pour me faire livrer 3 mascaras , cela m'en coûterait 27 euros ! ! ! ! et depuis qq temps , les commandes sont facilement jugées trop volumineuse . impossible donc de me faire livrer un shampoing ! ! ! ! ! on se moque du monde ! ! ! !",1,1,1

In [ ]:
# obligé de reprendre les données ici car bert n'a pas été entrainé sur dataset_final.pkl, donc j'avais un problème de matching entre les embeddings et les textes
df = pd.read_csv("../data/preprocessed/reviews_trust_clean.csv")
df_sans_contexte = pd.read_csv("../data/preprocessed/reviews_trust_clean_stopwords_supprimer.csv")

# on retire quelques stopwords supplémentaires
stopwords_custom = {
    'montre', 'montres', 'boucle', 'boucles', 'oreilles', 'oreille', 'paire', 'paires', 'lunettes', 'bracelet', 'bracelets', 'collier', 'iphone', 'téléphone', 'pendentif', 'robot', 'robots', 'aspirateur', 'baskets', 'basket', 'chaussure', 'chaussures', 'sandales', 'plantes', 'plante', 'arbres', 'arbre', 'bulbes', 'willemse', 'sommiers', 'jardin', 'bague', 'lampe', 'lampes', 'abat-jour', 'abat jour', 'lampadaire', 'parfum', 'shampoing', 'shampooing', 'shampooings', 'cheveux', 'masque', 'masques', 'crème', 'élastiques', 'manteau', 'bougie', 'cadre', 'écouteurs', 'vélo', 'robe', 'vêtements', 'bijoux', 'sac', 'portable', 'clio', 'luminaire', 'oreillette', 'induction', 'écouteur', 'couette', 'samsung', 'téléphones', 'smartcase', 'abat', 'apple', 'watch', 'shirt', 'tee', 'chemise', 'shirts', 'hortensias', 'orchidée', 'sacs', 'plant', 'chaises', 'lacoste', 'polo', 'pantalon', 'jean', 'jeans', 'sneakers', 'lunette', 'écran', 'tablette', 'tablettes', 'table', 'tables', 'chemisier', 'pulls', 'pull', 'trotinettes', 'trotinette', 'chaussons', 'chausson', 'brosse', 'brosses', 'crèmes', 'gel', 'gels', 'parfums', 'robe', 'robes', 'sacoches', 'sacoche', 'vestes', 'veste'
}

def clean_custom(text):
    tokens = text.lower().split()
    tokens = [t for t in tokens if t not in stopwords_custom]
    return " ".join(tokens)

df_sans_contexte["clean_comment"] = df_sans_contexte["clean_comment"].apply(clean_custom)
df["clean_comment"] = df["clean_comment"].apply(clean_custom)

# on conserve que les commentaires de plus de 100 caractères
mask = df["clean_comment"].str.len() > 100

df = df[mask]
df_sans_contexte = df_sans_contexte.loc[df.index]

texts_sans_contexte = df_sans_contexte["clean_comment"].astype(str).tolist()
texts_avec_contexte = df["clean_comment"].astype(str).tolist()

# # Si on modifie encore les stopwords et qu'on veut regénérer les embeddings, décommentez le code ci-dessous
# # --------- Pour regénerer les embeddings, décommentez le code ci-dessous ---------
model = SentenceTransformer('dangvantuan/french-document-embedding', trust_remote_code=True)
X_ctx = model.encode(
    texts_avec_contexte,
    batch_size=32,
    show_progress_bar=True
)
with open("../data/embeddings/emb_sbert_fr_ctm.pkl", "wb") as f:
    pickle.dump(X_ctx, f)
# # --------- Pour regénerer les embeddings, décommentez le code ci-dessus ---------


with open("../data/embeddings/emb_sbert_fr_ctm.pkl", "rb") as f:
    X_ctx = pickle.load(f)
    
X_ctx = np.asarray(X_ctx)
assert X_ctx.shape[0] == len(texts_avec_contexte), "Mismatch nb docs vs nb embeddings"

Batches:   0%|          | 0/259 [00:00<?, ?it/s]

In [21]:
tp = TopicModelDataPreparation("camembert-base")

training_dataset = tp.fit(
    text_for_contextual=texts_avec_contexte,
    text_for_bow=texts_sans_contexte,
    custom_embeddings=X_ctx
)

bow_size = len(tp.vocab)
ctx_size = X_ctx.shape[1]
bow_size, ctx_size

(20043, 768)

In [22]:
K = 30 # nombre de topics
ctm = CombinedTM(
    bow_size=bow_size,
    contextual_size=ctx_size,
    n_components=K,
    num_epochs=20,
    num_data_loader_workers=0
)

ctm.fit(training_dataset) # entraînement

Epoch: [20/20]	 Seen Samples: [165120/165580]	Train Loss: 382.26541942034584	Time: 0:00:02.289934: : 20it [00:46,  2.33s/it]
100%|██████████| 130/130 [00:01<00:00, 82.83it/s]

In [23]:
topics_words = ctm.get_topic_lists(20)  #  le nombre de mots à afficher par topic
for k, words in enumerate(topics_words):
    print(f"Topic {k}: {', '.join(words)}")

Topic 0: livreur, domicile, reçue, poste, recu, déposé, bureau, chercher, lettres, passage, laissé, journée, retirer, mains, quelqu, dpd, allée, dites, facteur, gls
Topic 1: endommagé, rétracter, madame, imaginer, falloir, droits, paquets, plateau, mention, nulle, satisfait, sent, courage, physique, abîmé, existait, revoir, laissée, recevrais, correctement
Topic 2: est, plus, qu, site, vente, remboursement, ai, service, être, fois, faire, client, fait, mail, avoir, depuis, privée, bien, après, retour
Topic 3: colis, mail, qu, service, remboursement, commande, jours, ai, après, relais, part, demande, chez, client, faire, jamais, donc, est, rien, avoir
Topic 4: tissus, tailles, taille, irl, qualité, agréable, recommanderai, collection, bottines, finitions, aime, grand, longues, dessus, pied, grandes, sortent, garde, rapides, connais
Topic 5: permets, 98, partager, matériel, existait, grandir, autorise, rendent, foutage, résumé, trouvent, membre, 2000, page, rythme, sommier, fonctionnera, médiocrité, savez, inquiet
Topic 6: site, vente, plus, est, retour, euros, si, frais, privée, ai, faire, car, non, bon, tout, alors, prix, qu, bien, une
Topic 7: remboursements, voleurs, honte, voyage, appels, fuir, incompétent, relances, reponse, nul, apres, explication, inadmissible, inexistant, mails, covid, clientèle, escrocs, scandaleux, nez
Topic 8: messieurs, existait, physique, laissée, pot, lois, incidence, déplacement, faible, casseroles, réponde, rétracter, autorise, rappellera, inquiet, enrichir, retourc, apparaissait, promettant, insistance
Topic 9: rapport, 42, xl, plastique, qualité, irl, image, sommier, redire, elles, moyenne, habituelle, niveau, large, déçue, top, joli, essayer, modèles, échanger
Topic 10: taille, 38, petit, bonne, fille, petite, tissu, correspond, peu, irl, matière, porter, préciser, beau, pointure, recommande, mesures, belle, qualité, couleurs
Topic 11: voie, chaise, rétracter, engage, écrite, responsabilité, remarque, rappellera, existait, horaires, fermoir, acceptée, dites, grade, négocier, incidence, engagé, lâcher, grandir, gain
Topic 12: qualité, marque, marques, frais, prix, produits, article, trop, commandé, retour, articles, 50, plastique, sites, acheter, trouve, port, bref, acheté, autres
Topic 13: vente, est, ai, site, qu, privée, plus, euros, si, alors, produit, un, donc, faire, tout, une, après, cette, très, il
Topic 14: voyage, fuir, annulé, honte, déconseille, malgré, société, veepee, séjour, déplorable, voleurs, débité, fuyez, plateforme, solution, réponses, étoile, depuis, relances, mettre
Topic 15: carton, abîmé, manquait, lettres, boîte, ouvert, cassé, moitié, déchiré, intérieur, remplacé, chance, abîmés, emballage, flacons, contenu, boite, arrivés, scotch, paquet
Topic 16: page, 180, ressemble, prochainement, retient, celles, matières, heureux, recommanderai, lâcher, sachez, regrette, médiocrité, deja, facile, pointure, grandir, regrouper, reçus, 41
Topic 17: merci, respecté, satisfaite, prévue, écrite, emballage, tôt, arrivée, attentes, rapide, parfait, date, parfaitement, emballé, prévu, 180, endommagé, avance, explosé, conforme
Topic 18: 800, grandir, faible, écrite, neuf, vrais, fassent, chiffre, plate, confirmée, refusez, lois, incidence, coupons, alor, rétracter, disponibilité, mienne, flash, constater
Topic 19: service, commande, remboursement, mail, client, ai, qu, après, colis, donc, bien, livraison, demande, plus, être, est, dit, faire, chez, reçu
Topic 20: toujours, décembre, 12, 21, 15, novembre, passée, nouvelle, livrée, colis, janvier, commande, livré, aucune, 24, livraison, enquête, showroom, suivi, rien
Topic 21: après, remboursement, problème, toujours, commande, veepee, réponse, service, être, mail, rien, argent, jamais, fois, mois, fait, faire, depuis, attends, rembourser
Topic 22: commandé, deux, fois, depuis, commander, remboursé, mois, jamais, site, vais, après, suite, avoir, car, être, problème, quand, non, contacté, veepee
Topic 23: prix, cher, trouve, arnaque, port, parfois, marques, acheter, retours, vendu, bonnes, réduction, lieu, ailleurs, souvent, autres, croire, sites, attention, vérifier
Topic 24: 2020, 11, toujours, juin, 20, juillet, novembre, avril, réclamation, passée, livraison, livré, mai, retard, 18, 24, livrée, noël, date, devait
Topic 25: arnaque, attention, cher, grosse, 99, achetez, affaires, amazon, acheter, erreurs, sites, fidèle, croire, faites, magasin, retours, défectueux, gonflés, comparer, privées
Topic 26: indiquée, longue, belle, ravie, super, jolie, conforme, satisfaite, rapide, beau, joli, sommier, résumé, commandées, grands, rendu, magnifique, couleurs, avance, description
Topic 27: commande, colis, qu, livraison, jamais, remboursement, service, dit, mail, toujours, jours, avoir, cette, chez, fait, fois, part, faire, bien, demande
Topic 28: explication, éviter, réponses, joindre, inexistant, voleurs, apres, déconseille, scandaleux, électrique, covid, incompétence, incompétent, veulent, débité, trésorerie, insupportable, fuyez, derniers, commandez
Topic 29: commandé, commandes, commander, article, renvoyer, achat, déçue, erreur, deux, bon, mauvaise, articles, cliente, payé, moment, années, retour, envoi, site, frais

In [24]:
doc_topic = ctm.get_doc_topic_distribution(training_dataset)  # shape (n_docs, K)
df["topic_id"] = np.argmax(doc_topic, axis=1)
df["topic_confidence"] = doc_topic.max(axis=1)

100%|██████████| 130/130 [00:01<00:00, 80.34it/s]

In [13]:
os.makedirs("./artifacts/ctm", exist_ok=True)
os.makedirs("./artifacts/ctm/exports", exist_ok=True)

# ctm.save(models_dir="./artifacts/ctm/model")

# with open("./artifacts/ctm/vocab.pkl", "wb") as f:
#     pickle.dump(tp.vocab, f)

pd.DataFrame({
    "topic_id": np.arange(len(topics_words)),
    "top_words": [", ".join(w) for w in topics_words]
}).to_csv("./artifacts/ctm/exports/topics_top_words.csv", index=False)

np.save("./artifacts/ctm/exports/doc_topic.npy", doc_topic)

df.to_csv("./artifacts/ctm/exports/reviews_with_topics.csv", index=False)

In [25]:
topic_counts = df["topic_id"].value_counts().sort_index()
display(topic_counts)

topic_id
0     349
1     205
2      31
3      34
4     340
5      90
6     130
7     378
8     141
9     201
10    378
11    180
12    263
13     36
14    617
15    550
16    274
17    519
18    303
19     44
20    282
21    337
22    380
23    233
24    380
25    241
26    280
27     84
28    446
29    553
Name: count, dtype: int64

In [34]:
# Exemple de quelques commentaires par topic
def examples_for_topic(t, n=5):
    return df[df["topic_id"]==t]["clean_comment"].head(n).tolist()

for t in range(K):
    ex = examples_for_topic(t, 10)
    print(f"\n=== Topic {t} ===")
    for e in ex:
        print("-", e[:])


# 100 commentaires par catégories
# --- Définition des groupes de topics ---
# topics_livraison = [0, 3, 15, 17, 19, 20, 24, 27]
# topics_service_client = [1, 2, 6, 7, 8, 11, 14, 18, 21, 22, 23, 25, 28]
# topics_qualite_produit = [4, 9, 10, 12, 13, 16, 26, 29]

# # --- Fonction pour récupérer un nombre donné d'avis par catégorie ---
# def sample_by_topics(topic_list, n=100):
#     df_filtered = df[df["topic_id"].isin(topic_list)]
#     # si moins de 100 avis, on prend tout
#     return df_filtered["clean_comment"].sample(min(n, len(df_filtered)), random_state=42).tolist()

# # --- Récupération des 100 avis ---
# livraison_examples = sample_by_topics(topics_livraison, n=100)
# service_client_examples = sample_by_topics(topics_service_client, n=100)
# qualite_produit_examples = sample_by_topics(topics_qualite_produit, n=100)

# # --- Affichage propre ---
# def print_examples(label, examples):
#     print(f"\n=== {label} : {len(examples)} avis ===")
#     for e in examples:
#         print("-", e[:200])  # tronquer à 200 caractères pour lisibilité

# print_examples("SERVICE LIVRAISON", livraison_examples)
# print_examples("SERVICE CLIENT", service_client_examples)
# print_examples("QUALITÉ PRODUIT", qualite_produit_examples)

=== Topic 0 ===
- vente article manquant photo prise sur 6 articles la moitié livrée sans explication manque de respect.numero de commande 230130353
- commande passée pour une vente , livraison 15 nous après la date prévue , déjà 6 semaines après l'achat , sur 3 produits , 2 manquants . pas pro , pas sérieux , aucun geste commercial hormis le remboursement promis des 2 articles manquants .
- ça fait un mois que ma commande aurait du être livré et showroom fait traîner l ’ affaire malgré mes appels et messages pourtant chronopost m ’ a indiqué le colis comme perdu
- dernièrement j'ai publié un avis mentionnant ma mauvaise expérience lors de l'achat d'un lot de boxers fila.après plusieurs échanges avec showroomprive , le services clients a finalement accepté que je retourne les articles . leur analyse a abouti à la décision de me rembourser.bravo showroomprive pour avoir accepté de revoir votre position .
- très deçu . j'ai commande une valise qui n'est jamais arrivée mais marquée comme livrée avec comme signature `` gardien '' sachant qu il n ' y aucun gardien dans ma résidence et que j'etais chez moi toute la journée .... toute une demarche pour faire une réclammation : attestation sur l'honneur , photocopie cni , et process qui dure 16 jours .... j'espere bien être remboursée ou que l'article soit renvoyé . changez de transporteur showroom ( gls dans mon cas ) . c'était ma 1ère commande , ca sera la dernière .
- j'ai deux commandes en cours , la première n'est jamais arrivée entière . depuis l'enlèvement du colis je suis toujours en attente de mon remboursement . pour la seconde commande , on m ' a prévenu qu'il ne savait pas où était tous les colis . fuyez , je ne sais pas quoi faire .
- bjrachat d ’ un trampoline il y a un mois1 colis reçu sur 31 retourné à l ’ expéditeur et 1 autre en instance ds l ’ agence de dpd depuis 4 semaines je contacte le sav de showroom à 5 reprises sur cette et rien ne se passe j ’ ai un colis qui m ’ encombre chez moi et je n ’ ai pas été remboursé mes enfants attendent avec impatience ce trampoline qui n ’ arrivera jamais ...
- j ai renvoyé un colis qui est arrivé cassé ( meuble tv ) cela fait 5 mois que j attends le remboursement sans nouvelles de leur part .... très déçu ! en + on me dit qu ’ il n est plus dispo alors que il est toujours en vente sur le site ..... ! ! ! !
- j ’ avais l ’ habitude de commander showroomprive aujourd ’ hui je suis déçue ! ! une commande livrée dans une autre région ! ! pas même une autre ville non ! ! une autre région et on me dit qu ’ il faut faire une investigation qui va durer 15 jours pour comprendre pourquoi le colis est indiqué livré ! ! ou est le bon sens ! ! !
- suite à une commande le point relais a étais changer en me disant qu ’ il était fermé hors auchan est ouvert tout le temps suite à ça livraison retardée pour à la fin au bout de 1 mois me dire commande annulée sans raison ayoub ne prend pas la peine de répondre merci je ne commanderai plus chez vous .

=== Topic 1 ===
- je n ’ ai pas aimé commander sur ce site parce que la livraison était vraiment nul j ’ ai appelé comme on me l ’ a suggéré dans mon avis et ça n ’ a pas fait avancer grand chose dommage
- malheureusement les produits sont souvent mal emballés et donc quelques déboires lors de la réception de la commande .
- bonjour , commande très déçu sur ma commande de salon de car les barres de étaient piqués et légèrement rouillé obligés d'acheter de la peinture dommage pour ma première commande
- j'ai reçu ma commande de leecooper aujourd'hui incomplète . il me manque 1 jogging1 sweat capuche 1 à capuchej'aurai le reste ou un remboursement ?
- très déçue j ’ ai commandé une trépied qui n ’ est jamais arrivé , j ’ ai dû les relancer énormément de fois en espérant qu ’ ils me remboursent bien comme convenu et que le reste de mes commandes arrivent !
- attention . le retour a votre charge . même si l'article reçu n'est pas celui la que a été commandé .
- bonjour , pour une première fois que je commande sur horoomprivé , je suis déçue , faite attention au akribo sur horoomprivé car une bien présente mais sur le site mais à la livraison l ' emballage est abîmé , en plus la ne fonctionne pas franchement c est decevrant il y a beaucoup de personnes qui se plein concernant les akribo
- aucun problème pour la réception de ma commande . par contre , la politique de retour est à revoir ... aucun point relais pour déposer son colis , j ai du aller à la poste et payer 8e pour mon retour ... pas sure que je repasse commande
- j'ai retourné un produit par mes propres moyens mais sur le remboursement on m ' a quand même déduit 6.95€ .... une seconde commande passée pour 2 articles et l'un des 2 articles n'est absolument pas celui commandé , ni le modèle ni la taille ! ! !
- produit arrivé abîmé . on me refuse un retour car soit disant le délai est dépassé alors que pour un défaut de conformité le délai est de 2 ans ! ! site malhonnête , responsable menteurs . à fuir ! !

=== Topic 2 ===
- scandaleux , honteux et immoral ! avant j'étais cliente fidèle et heureuse de sp , mais dernièrement c'est vraiment d ' y n'importe quoi , je suis en colère car ils sont : immoraux , incompétents , malhonnêtes , irresponsables et menteurs.problème commande n°1 224968553j'ai commandé un de la marque mauboussin pour l'anniversaire d'un ami , avec les bons d'achat de 15€ qu'on m'avait offert suite à une annulation unilatérale de ma commande . j'étais contente d'avoir le à ce prix , bonne nouvelle le colis a été livré au point de relais avant l'anniversaire de mon ami.au point de relais la vendeuse remarque que la boîte est vide , je l'ouvre devant elle et il n ' y a rien . je les appelle le jour même et ils disent me rembourser dès la réception du colis , le colis arrive deux jours après et dans leur site , ils n'ont pas procédé à l'annulation de cette commande , je les ai encore appelé et ils ont dit de patienter 14 jours , ils ont reçu le colis le 22 mars et aujourd'hui le 6 avril , je ne suis toujours pas remboursé , qu'elle bande de malhonnêtes , après cet incident , je ferme mon compte et je ne veux plus de leur bons d'achat à 2 sous qu'ils volent dès qu'ils peuvent.le remboursement devait être automatique suite à la réception du colis dans ce genre de situations et de l'analyse de celui-ci ! amazon rembourse pour moins que ça , même juste pour mécontentement du client ou pire 3 étoiles sur une commande , mais sp est d'une complexité incroyable et surtout d'une fervente mauvaise foi ! problème commande n°2 224968976j'étais contente de cette en cuir , j'étais dans la rue et elle se dechire sur le côté , je suis obligée de l'ouvrir vu que j'étais dehors et j'avais des courses à faire , il faisait froid , impossible de fermer une avec un gros trou . elle s'est totalement déchirée , problème d'usure et de qualité , c'est une isaco & kawa , vente qui revient systématiquement sur le site , dont des clients se sont déjà plainte pour sa piètre qualité . la déchirure est telle que je prends une photo , je n'ai jamais vu une en cuir se déchirer ainsi et pourtant c'était ma taille et j'en ai plusieurs . comme toujours ils ne peuvent pas renvoyer un autre article car `` gne gne la vente est terminée '' .site de clowns sérieusement , les autres marchands procèdent à un renvoi ou un remboursement sans autant de malhonnêteté . c'est toujours unilatérale avec sp , ils remboursent quand il veulent et annulent la commande quand ça leur chante.la devait certainement être une en smilicuir et non en cuir comme annoncé par sp.j'ai renvoyé à mes frais 9€15 par colissimo , ils vont prendre des années pour me rembourser je sens ... conclusion : évitez shoowromprivé car quand vous avez des problèmes ils ne sont jamais là , les problèmes sont souvent les mêmes : usure , contrefaçon , annulation unilatérale , incapacité de renvoyer un autre produit , ils ne le font jamais ! ! site qui dépend entièrement de ses fournisseurs , comme pour le qu'ils n'ont pas pu me renvoyer ou rembourser dans l'immédiat alors que le transporteur a renvoyé l'objet que j'ai refusé de retirer au point de relais , donc je ne sais pas ce qu'ils attendent , je suis extrêmement en colère . favorisez bazarchic qui fonctionne beaucoup mieux et qui est plus pro , boycottez ce site qui ne respecte pas ses clients ! j'attends un remboursement immédiat de la vente mauboussin showrooprivé sinon nous sommes dans une affaire grave d'escroquerie , je pourrais contacter les associations de consommateurs ou je vais contacter la presse !
- quelle déception de recevoir autre chose que ce que l'on a commandé surtout quand il s'agit d'un gros cadeau à mettre sous le sapin ! et le service client au ose vous souhaiter de bonnes fêtes ! on les prépare ces fêtes à l'avance afin qu'elle soit bonne justement et grâce à cette malheureuse commande c'est mal parti ! j'ai commandé le fameux camping car lol surprise et je reçois un jouet pour bébé ! c'est cher 99 euros pour un jouet de bébé qui ne m'intéresse pas du tout ! comment est-ce possible de se tromper à ce point , sur des cela peut arriver , mais des jouets aussi gros c'est pas des qu'il faut à vos préparateurs de commande mais un cerveau pour réfléchir ... je me demande bien comment c'est possible vu la taille du colis , les 2 jouets n'ont aucune ressemblance , jamais vu cela auparavant ! j'ai renvoyé votre jouet de bébé et j'espère que le remboursement de cette commande inutile va être extrêmement rapide et je dois être remboursé de la somme entière rien n'est à déduire , il est hors de question de perdre le moindre euro sur cette commande qui m'aura fait perdre mon temps et le pire cette somme d'argent qui pour l'instant est bloquée chez vous pour rien et je dois pour passer de bonnes fêtes justement , acheter ailleurs ce fameux camping car lol puisque on ne peut pas vous faire confiance ! donc , il me faut rapidement mon remboursement total au plus vite , je ne suis pas responsable de votre incompétence mais j'en subi les conséquences !
- je n'ai jamais vecu une si mauvaise expérience ailleurs ! d'habitude je commande chez un autre commerçant en ligne . je n'ai jamais eu de soucis avec l'autre site.chez showroomprivee j'ai passé seulement 2 commande jusqu ' à là . la première est toujours en cours de livraison .. mais j'ai déjà eu beaucoup de soucis avec la deuxième commande : en effet j'ai passé une commande sergent major la semaine dernière pour ma sœur . j'ai reçu le colis ce matin.et là , la grande surprise ! ! ! sur les 5 articles commandés , ils m'ont envoyé 2 mauvais articles ! pour un t-shirt du 9 mois commandé , j'ai reçu un femme de la taille 46 d'une autre enseigne ! pour une à capuche du 24 mois , j'ai reçu un ! j'ai contacté le service client après avoir envoyé toutes les photos demandées , ils m'ont proposé un bon d'achat de 10 euros si je suis d'accord poue garder ces articles dont un grande taille xxxl . pardon ? ça va pas showroomprivee ? j'ai payé 15,40 euros pour ces deux articles sans compter les frais de port dedans ! puis ils m'ont proposé de leur retourner les mauvais articles .. je serai remboursé sous 14 jours . les démarches pour un retoursont très très compliquées chez eux , car ça ne fonctionne pas sur le ni sur la tablette.c'est un vrai casse-tête ! je ne dispose pas d'ordinateur chez moi ! je suis obligé de demander à mes parents de se connecter sur mon compte et essayer d'imprimer les bordereaux de retour ! parce que le service client refuse de me les envoyer par mail ! de plus , depuis le premier confinement le bureau de poste chez nous est ouvert du mardi au vendredi de 9h à 12h ! je n'ai aucune idée comment y rendre pour déposer le colis pendant mes horaires de travail ! ! ! a fuir ! ! ! a éviter ! ! aucun respect pour ses clients surtout les nouveaux clients ! ils se rendent compte que les autres sont très embêtés par leurs erreurs ? ils croient que les gens n'ont pas d'autres choses à faire ! pour 15,40 euros , je dois embêter mes parents pour l'impression du bordereau de livraison et le dépôt du colis ! je suis vraiment en colère ! ils ne sont pas sérieux du tout ! comment on a pu envoyé à ses clients 2 mauvais articles sur 5 commandés ! ! sérieux ? lol
- je n'avais jusqu ' à présent jamais commandé sur ce site , j'aurais mieux fait de m'abstenir.vente de goby qui semblaient plutôt sympathiques , je décide donc d'acheter une , n'arrivant pas à choisir , mon copain me propose de m'en offrir une également.déjà , en tant que nouvelle cliente , j'étais sensée recevoir un bon d'achat de 10 ou 12€ pour toute première commande qui devait être crédité directement sur mon compte , je ne l'ai jamais reçu , après avoir contacté le service client , ils me répondent que c'est uniquement pour les clients de belgique .... faux , car une amie qui vient tout juste de créer son compte en même temps que moi a bien reçu son bon d'achat à activer par email , elle habite en france et utilise aussi le site français.soit , marre de me battre et d'attendre car la vente va se terminer , les deux achats sont donc effectués , un sur mon compte , le second avec le compte de mon copain.les deux commandes sont en préparation et seront livrés le 7 novembre , jusque là , tout va bien.quelques jours plus tard , impossible d'accéder à mon compte , je reçois un email m'indiquant que ma commande est annulée sans véritable raison et qu'elle sera remboursée , remboursement qui est à suivre sur le site .... auquel je n'ai plus accès.je contacte le service client par qui m'indique que le paiement a été effectué avec une `` carte frauduleuse '' et que la vente a été bloquée pour ces raisons.ma carte n'est pas frauduleuse , mon compte en banque est bien alimenté et pour preuve , la somme s'est prélevée sans aucun problème.on me dit que l'information est remontée et que je serais recontactée sous 5 jours pour que mon compte soit débloqué.pour mes ? `` tant pis pour moi '' , malgré le fait que ce soit une erreur de leur part , la vente est finie , il faudra attendre la suivante s'il y en a à nouveau une .. génial.plus de deux semaines plus tard , mon compte est toujours inaccessible et je n'ai eut aucun retour concernant ce soit disant problème de carte frauduleuse.puis vient le deuxième problème , je reçois en avance la de commandée via le compte de mon compagnon.horrible . un produit qui n ' a absolument rien à voir avec les photos , lacets marrons au lieu de moutarde , motifs étirés et mal appliqué sur toute la et couleur totalement délavée qui tend vers le gris au lieu de couleurs vives , article défectueux , contrefaçon , aucune idée mais elles ne valent absolument pas 60€ , 25€ à tout casser si on est pas très regardant.je recontacte le service client .. encore une fois , qui me demande des photos pour preuve et qui me proposera une solution après réception , soit un retour du produit avec remboursement , ce qui ne m'arrange pas forcément avec cette période de confinement et certains points relais qui n'acceptent pas les retours de produits , soit un remboursement partiel et je garde les soit un geste commercial de showroom privé.la réponse est tombée aujourd'hui on me demande soit de renvoyer le produit , comme dit précédemment , choix très compliqué , soit de le garder et d'accepter un bon d'achat de 10€ à utiliser dans les 3 mois .... un bon d'achat de 10€ pour un achat defectueux a 60€ avec obligaiton de rachat sur un site malhonnete dans les 3 prochains mois.on se moque de qui ? et au vu des commentaires postés ici , j'ai même l'angoisse de renvoyer mon paquet et qu'il `` se perde '' ou `` arrive vide '' , ou je ne sais quel autre mensonge encore et de perdre la totalité de mon argent ..
- j'ai commandé un tuyau d'arrosage extensible de bonne marque puisque le vendeur garantit 2 ans son produit au bout de 2 mois l'enveloppe de ce dernier s'est déchirée à 3 endroits différents bonjour la qualité .... je fais jouer la garantie et là la galère commence on me balade entre showroom qui dit que c'est le vendeur et le vendeur qui me dit que c'est showroom . j'envoie un mail au service clientèle de showroom qui m'envoie une étiquette prépayée et un bon de retour , j'ai trouvé l'adresse bizarre mais bon je l'envoie 15 jours après le colis revient avec npai sur le colis . je à showroom pour leur expliquer que l'adresse de l'étiquette n'est pas bonne , je tombe sur une personne qui me prend pour une imbécile et me renvoie une étiquette de retour avec la même adresse , je renvoie le colis en me disant que la poste n'avait peut être pas trouver l'adresse et là ça revient 15 jours après avec de nouveau `` n'habite pas à l'adresse indiquée '' . de colère j'envoie un mail parce que c'est une personne de 74 ans qui se déplace pour rien et la réponse c'est quelques excuses avec une autre étiquette mais cette fois ci il faut aller au relais colis qui est à plus de 15 kilomètres donc c'est à moi de payer les frais de déplacement . celà fait plus de 10 ans que je suis cliente chez eux avec des achats assez réguliers et conséquents mais même pas un geste commercial ni ni un bon d'achat pour s'excuser . contrairement à vente privée leur service clients est incompétent et n ' a pas le sens du commerce . ils vont perdre un client entre 500 et 600 euros de commandes par an pour un tuyau à 24.99 euros . je déconseille fortement ce site
- suite à une commande passée pour des conteneurs à croquettes , colis récupéré en relais colis , cartons totalement abîmés et une fois le déballage effectué , conteneurs cassés ( 2 colis différents même résultat ) .petit mail au sav qui me dit de voir avec la garantie fournisseur . ( ils n'ont pas dû lire le mail ) du coup j'appelle et là on me dit pas de soucis vous allez être remboursé des articles pas besoin de les renvoyer.5 min plus tard , 1 appel m'informant que finalement , après avoir vu avec son chef , je dois renvoyer les articles et on verra pour le remboursement à réception ... entre ça et les articles qui manquent souvent dans les colis , showroomprivee et moi c'est fini ...
- commande ice-watch effectuée récemment sur le site , colis reçu : 2 produits yves rocher pour se laver les mains ! on ne me l'avait encore jamais fait celle la ! ! je contacte le service client pour exposer les faits : pas de souci on va vous rembourser ( ba oui pas de stock donc je ne verrais jamais la couleur de la ) on me demande quand même de renvoyer les produits reçus ( ce que je fais ) et aujourd'hui je reçois un e-mail de leur part : nous avons bien réceptionné le ( s ) article ( s ) de votre commande ice-watch . toutefois , un ou plusieurs produits de ce retour ne peuvent être ni repris ni échangés.comme stipulé dans l ’ article 7 de nos conditions générales de vente , certains produits ne sont pas éligibles au droit de rétractation . de plus , seuls les produits présents dans le colis et conformes à ceux indiqués sur le formulaire de retour peuvent être traités et acceptés . votre retour ne respectant pas les conditions évoquées , nous sommes dans l ’ incapacité de prendre en compte le retour de votre colis . nous vous renverrons donc , à l'adresse de livraison initiale de votre commande , votre colis comprenant le ( s ) produit ( s ) suivant ( s ) dont nous ne pouvons pas traiter et accepter le retour * : ice-watchj'espère que c'est une blague showroomprive ! ! et que vous allez rapidement me rembourser les 49€ que vous me devez ! terminé les achats sur votre site , ce n'est pas la première fois que j'ai des problèmes avec mes commandes ... fini

In [28]:
#Évaluer la diversité des topics
def topic_diversity(topic_words):
    """
    Calculate topic diversity: proportion of unique words among top words of all topics.
    topic_words : list of lists, each sublist contains the top words of a topic.
    """
    top_words = []
    for words in topic_words:
        top_words.extend(words)

    unique_words = set(top_words)
    diversity = len(unique_words) / len(top_words)
    return diversity
diversity_score = topic_diversity(topics_words)

print(f"Diversité des topics: {diversity_score:.2f}") # closer to 1 : each topic uses unique words(good diversity)

Diversité des topics: 0.66

In [29]:
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora import Dictionary

# texts : liste de documents, chaque document = liste de tokens
# topic_words : liste de listes des mots top de chaque topic
texts = df_sans_contexte["clean_comment"].apply(lambda x: x.split()).tolist()
dictionary = Dictionary(texts)

cm = CoherenceModel(
    topics=topics_words,
    texts=texts,
    dictionary=dictionary,
    coherence='c_v'
)

coherence_score = cm.get_coherence()

print("Score de cohérence:", coherence_score)

Score de cohérence: 0.4528591754957337

In [30]:
for c in df[df["topic_id"] == 0]["Commentaire"]:
    print(c, "\n---\n")

Vente lacoste article manquant photo prise sur 6 articles la moitié livrée sans explication manque de respect.Numero de commande 230130353
---

Commande passée pour une vente Lacoste , livraison 15 nous après la date prévue , déjà 6 semaines après l'achat , sur 3 produits , 2 manquants . Pas pro , pas sérieux , aucun geste commercial hormis le remboursement promis des 2 articles manquants .
---

Ça fait un mois que ma commande aurait du être livré et Showroom fait traîner l ’ affaire malgré mes appels et messages Pourtant Chronopost m ’ a indiqué le colis comme perdu
---

Dernièrement j'ai publié un avis mentionnant ma mauvaise expérience lors de l'achat d'un lot de boxers FILA.Après plusieurs échanges avec Showroomprive , le services clients a finalement accepté que je retourne les articles . Leur analyse a abouti à la décision de me rembourser.Bravo Showroomprive pour avoir accepté de revoir votre position .
---

Très deçu . J'ai commande une valise qui n'est jamais arrivée mais marquée comme livrée avec comme signature `` gardien '' sachant qu il n ' y aucun gardien dans ma résidence et que j'etais chez moi toute la journée .... toute une demarche pour faire une réclammation : attestation sur l'honneur , photocopie CNI , et process qui dure 16 jours .... j'espere bien être remboursée ou que l'article soit renvoyé . Changez de transporteur showroom ( GLS dans mon cas ) . C'était ma 1ère commande , ca sera la dernière .
---

J'ai deux commandes en cours , la première n'est jamais arrivée entière . Depuis l'enlèvement du colis je suis toujours en attente de mon remboursement . Pour la seconde commande , on m ' a prévenu qu'il ne savait pas où était tous les colis . Fuyez , je ne sais pas quoi faire .
---

BjrAchat d ’ un trampoline il y a un mois1 colis reçu sur 31 retourné à l ’ expéditeur et 1 autre en instance ds l ’ agence de DPD depuis 4 semaines Je contacte le SAV de Showroom à 5 reprises sur cette et rien ne se passe J ’ ai un colis qui m ’ encombre chez moi et je n ’ ai pas été remboursé Mes enfants attendent avec impatience ce trampoline qui n ’ arrivera jamais ...
---

J ai renvoyé un colis qui est arrivé cassé ( meuble tv ) cela fait 5 mois que j attends le remboursement sans nouvelles de leur part .... très déçu ! En + On me dit qu ’ il n est plus dispo alors que il est toujours en vente sur le site ..... ! ! ! !
---

J ’ avais l ’ habitude de commander Showroomprive aujourd ’ hui je suis déçue ! ! Une commande livrée dans une autre région ! ! Pas même une autre ville non ! ! Une autre région et on me dit qu ’ il faut faire une investigation qui va durer 15 jours pour comprendre pourquoi le colis est indiqué livré ! ! Ou est le bon sens ! ! !
---

Suite à une commande le point relais a étais changer en me disant qu ’ il était fermé hors auchan est ouvert tout le temps suite à ça livraison retardée pour à la fin au bout de 1 mois me dire commande annulée sans raison Ayoub ne prend pas la peine de répondre merci je ne commanderai plus chez vous .
---

Retour mal expliqué Mais c est ma faute car je n ai pas suivi leur procédure qui est expliqué nul partN° de commande 228272629
---

Je devais recevoir mon colis le 7 mai , par ma grande surprise ces décaler le 11 mai et actuellement toujours rien ! ! Je déménage bientôt et impossible de modifier mon adresse ! Aucun message et aucune modification à était fait sur la date de la livraison
---

Si ils ne mettent pas un mois à envoyer un colis , ils affichent `` en préparation '' pendant des plombes puis annule la commande , et cela a plusieurs reprises . Médiocre .
---

J'ai refusé ma commande de shampooings en point relais car colis éclaté et gluant ... montant de la commande : 61,09 € . Remboursement 25 , 80 € ! ! Réponse du service réclamations : bug technique ! ! En résumé : vérifiez bien vos remboursements ( la différence bien placée sur un compte sur plusieurs jours , ça doit rapporter ! )
---

j'ai passé une commande en octobre , mon colis a été livré dans un relais situé dans un autre département ceci en plein confinement , après s ’ être baladé entre l ’ entrepôt et le relais il était détérioré.Peu après la même vente a eu lieu , j'ai repassé une commande ... Le colis est resté dans la nature et m ' a été remboursé car détérioré ! ! ! Ceci sans explication .
---

Service client déplorable . J'ai payé un commande avec livraison à domicile obligatoire . On me livre un colis qui n'est pas le mien et aucun livreur n'est mandaté pour venir chercher ces cartons lourds et encombrants . Ma commande quant à elle ne m ' a jamais été livrée et ne m ' a pas été remboursée .
---

Le service client ne prend pas la peine de répondre.Je n ’ ai pas été informée de la réception de mon colis puis en allant à la pêche aux infos le relais colis avait changé et quand j ’ y suis allée il était fermé.Toujours aucune nouvelle de Showroom ...
---

Suite à un retour d ’ un produit en garantie et après plusieurs mails rapides , au début , avec le SAV je n ’ ai plus de nouvelles pour le suivi de ma réclamation pour obtenir mon remboursement . Depuis le 12/11/2020 c ’ est silence radio ....
---

commande effectuée le 26/11/2020 pour cadeaux de Noël , annulée par showroomprivé le 18/12/2020 pour une livraison prévue le 19/12 soit une semaine avant Noël , merci ......
---

Eh oui monsieur Ayoub pour Noël dans un papier Cadeau j offrirais vos excuses à la place des colis disparus faites au moins le geste de rembourser vos clients qui ils puissent offrir des présents pour les fêtes commande 215617438 sois disant expédiée le 21/11Commande216119821 sois disant expédiée le 26/11Commande217009348 sois disant expédiée le 01/12
---

Ma commande devait être livrée dans un relais colis à Vigneux-sur-Seine dans le 91 . Elle a été livrée dans le 77 en plein confinement . Le service client basé à l ’ étranger ne comprend pas que je demande à être indemnisé pour aller chercher le colis . Je me suis même fait crié dessus quand je leur ait dit que j ’ avais compris qu ’ ils étaient à l ’ étranger . C ’ est un cadeau de Noël !
---

1 mois de retard sur une livraison et toujours pas reçu ma commande . Service client catastrophique ! A FUIR
---

J ’ ai commander 2ensemble table de bar + tabouret L ’ une d ’ elle était complète , l ’ autre il manquait la barre de fixation centrale Showroomprivee me dit que le vendeur n ’ a pas de stock ni d ’ élément individuel pour remplacer Je demande le remboursement car je ne peux utiliser le tout Il me réponde qu ’ un livreur m ’ appellera pour convenir de rdv pour le retour de mon colis Je suis très mécontente La vente s ’ appelait « les must have mobilier »
---

Ne commandez surtout pas . Des incompetents . 2 colis perdus aucune communication . Des appels et mails toujours une reponse differente . Les colis ne sont jzmzis arrives au relais colis . Perdus maintenant et impossible de me faire rembourser . Ils menvoient un mail de reexpedition au meme relais colis mzis il est ferme . Je me tue a leur dire de livrer a un relzis ouvert . Et là silence et puis votre colis est perdu . Jarrive pas a me faire rembourser
---

Comme deux autres personnes . Toujours en attente de mon aspirateur Dyson v11 qui reste `` en cours de préparation '' depuis le 25.10.2020 alors qu'il devait être livre AU PLUS TARD le 31.10.2020
---

Problème toujours pas résolu un dénommé Ayoub m a recontacté il m a dit je vous recontacte sans faute mardi votre problème sera résolu et toujours rien c est le deuxième mardi la .....
---

13 jours que l'assistante de Showroom m ' a indiqué que Mr Ayoub me rappelait pour régler mon problème .... toujours aucune nouvelle .
---

Vraiment nul ! A fuir de toute urgence Colis noté livré au destinataire que je n ’ ai jamais récupéré ! 1 mois d ’ enquête , toujours au même point ... fuyez ces applis de chiottes ! ! !
---

J ’ ai commandé la marque de showroomprive et au niveau de la livraison c ’ est une catastrophe . Ils ont changé le point relais que j ’ ai choisi sans me demander mon avis . Les horaires indiqués ne sont pas les bons . Je n ’ ai toujours pas mon colis
---

Passer commande pour un anniversaire colis jamais arriver au point relais la livraison prévue le 19 septembre je fait 4 réclamation , je téléphone on me dit il faut attendre est la conclusion j ais soit disant retirer un colis qui n existe pas au point relais le 13 octobre facile de clore un litige avec les clients
---

Jai commandé pendant le confinement 100 euros de vêtements à orchestra , mais je nai jamais reçu mon colis ... malgré mes mails et mes appels pour réclamer , le service me dit simplement que le livreur atteste avoir livré dans al boire aux lettres .. ce qui est faux car je nai rien reçu !
---

bonjour 2 commandes passées qui ont été annulées de leur fait car problème d'approvisionnement à qq jours de la livraison ( montant très signicatif ) . et je passe les problèmes où ma carte bleue est refusée et mon paiement annulé ( banque ing ) .
---

I phone 11 commandé reçu non fonctionnel , j'ai donc renvoyé le produit , et cela fait plus de 15 jours que j'attends le remboursement , on me dit qu'ils vont faire le nécessaire mais je n'ai toujours rien et aucun retour de leur part sauf des mails automatiques .
---

J'ai annulé une commande N° 208108370 , je devais être remboursé ( 78,39 euros ) sous 5 jours , mais toujours rien ! Peut on me donner une explication ?
---

Commande arrivée en retard après une réclamation ... mais incomplètePas d ’ excusesCommande suivante prévue avec une semaine de retard sur la date prévueJe pense ne plus commander alors que je le fais depuis des annéesDommage
---

Attention escort commande passée puis envoyer le colis s est perdu par la poste retour chez eux puis annulation direct de la commande aucune possibilité de renvoyer l article . De plus la personne que j ' ai eu au téléphone lis des fiches avec un enfant qui joue derrière top . Bref remboursement de la commande et merci monsieur bonne journée a très vite chez shooroom privé .....
---

1 mois de retard a la livraison pour l'achat d'un lit et il me propose de me donner un bon d'achat de 15 euros ....
---

Bonjour , Pas moyen de joindre le service client pour cette commande qui devient en retard , voire très en retard.Actions sur ma commande : AUCUNEDate de livraison prévue 22/06/2020N° de commande : 1996323 ..... Serre de potager en bois avec composteurFabien
---

Première commande et quelle déception , un colis qui devait arriver en point relais il y a 11 jours et showroom privé qui fait le mort ...... un fiasco
---

Colis défectueux et très mal fermé.Également , je n ’ ai pas reçu mon second colis , aucun numéro de suivi , aucun mail de confirmation par contre concernant la facturation aucun problème.Il existe des formations professionnelles pour acquérir des compétences , il semblerait que Showroomprive ne soit pas au courant .
---

Très déçu , après 2mois a attendre ma commande je reçois un mail pour m avertir que le produit ne sera finalement pas livré ! , alors que sur le suivis de commande elle etait expédiée . J'attends 2 autre commandes de chz eux malheureusement je m'attends au pire.😔
---

service client inexistant . 1 article manquant lors d ’ une commande reçu il y a 1 mois . Le service client ne nous répond plus pas malgré de multiple relance . Nous avons payés un article jamais reçu . Bravo boite de voleur !
---

J'ai toujours pas reçu mon colis reliquat de ma commande j'ai fait déjà une réclamation le 16 juin qui manquait du matériel j'ai appelé j'ai téléphoné plusieurs fois pour savoir où se trouve le matériel il me répond il faut faire une enquête il faut attendre 14 jours aujourd'hui toujours pas reçu
---

Livraison de notre colis toujours en attente et cela après 15 jours d'attente . Il se rejette la balle avec relais colis . Entre incompétents on se serre les coudes . Pas capable de vous renseigner . Ça commence à bien faire les sites de ventes en ligne qui gère ça comme l'épicerie du coin . une honte
---

Tres déçu . Jai commandé une table . Qui devait etre livré il ya 15jours . Dans le suivi la table est livrée . Il ne faut pas en tenir compte . Elle arrivera un jour faut pas s'inquiéter me repond le service apres vente ! ! !
---

J ai reçu un colis non commandé , a la place de ma couette j ai reçu des pieds de table . showroomprive a annule ma commande de couette que j attendais depuis plus de 2 semaines sans m en avertir . J ai demandé a recevoir ma commande mais elle on m a dit pas en stock . La personne n a pas essayé de repondre a ma demande ekle a simplement mis la faute sur je ne sais quel service . Sav nul
---

Cela fait 2 fois d'affiler que le prestataire de livraison de showroomprivé , GLS ne me livre pas le colis et le retourne directemnt à l'expéditeur car trop volimineux.De son cotés showprivé prend plus de 3 mois pour effectuer le remboursement de ce dernier.Je ne recommande pas donc ce service , et ne l'utiliserai plus .
---

Service client incompétent : me soutien que j'ai reçu un colis que je n'ai pas reçu , malgrè de multiples appels et mails ...
---

Reçu une moitié de commande , une demi table et une demi armoire depuis attente d'un enlevement de la marchandise qui ne convient pas et toujours pas de remboursement et cela depuis le 23 mai
---

Très mauvais service client , sans doute situé à des milliers de kilomètre de chez nous . Incompréhension totale . J'attends depuis le mois de Mars l'étiquette de retour d'un oreiller à mémoire de forme qui ne me convient pas et livré sans protection , mis tel que dans le sac plastic d'expédition alors que normalement il devait être livré avec housse de transport . Après multiples mails et coups de téléphone , toujours rien . A éviter à l ' avenir ...
---

Colis soit disant livré , jamais reçu , commandé il y a presque 3 mois.Toujours pas de réponse malgré relances à part deux mails d'ouverture d ’ enquête et 15 jours de délais chaque fois ... Pas de commande , pas de remboursement ... A éviter pour ne pas perdre de temps ni de l'argent ...
---

Commande passée fin mars devait être livrée le 7 avril et toujours rien reçu au 8 mai.ils ne savent pas où est mon colis et ne veulent pas me rembourser c est scandaleux en plus d etre illégal
---

Une commande non livrée . J'attends depuis un mois que leur enquête aboutisse pour colis perdu . Pas moyen de se faire rembourser . Une honte ! A fuir .
---

Pour l ’ instant aucun soucis pour la livraison de commandes passées avant le confinement un peu de retard du fait que la poste ne distribue le courrier plus que 3 jours par semaine service client très réactif
---

Mon colis commandé le 7 mars n est jamais arrivé sous prétexte du coronavirus alors que j ai eu un autre colis cette semaine . Mensonges et refus de le rembourser et bien sûr c est moi qui ait dû les relancer . Sinon silence radio . Le service après vente m a raccroché au nez suite à mes emails . Bravo Shworoom . J attends mon remboursement .
---

J ai passer une commande en janvier pour un meuble industriel , quand je suis aller au point Relais ils m ont donner un seul colis ( Les pieds ) m informant que le reste suit , j ai été obligėe d annuler ma commande puisque le meuble par lui même c est évaporé dans la nature ! . Nous sommes debut mars toujours pas de remboursement 🤨🤨🤨
---

Ma commande a été annulée par showroom car le colis avait été abîmé par le transporteur . Malgré plusieurs relances téléphoniques et par mail , j'attends le remboursement de plus de 400 euros depuis plus d'un mois ! ! ! Évitez ce site de vente
---

Commande passée et encaissée bien sûr , livraison prévue le 27 décembre 2019.Nous sommes le 15 janvier 2020 , toujours rien reçu.Apparemment le colis a eu un problème lors de la livraison ... Je n'en sais pas plus ! ! ! ! !
---

Tres déçue du service client , commande livrée en retard pour Noël comprenant des cadeaux.Aucuns gestes , aucunes aides , on ne peut pas changer d'adresse , on ne peut pas annuler bref un service client qui ne sert à rien et ne respecte rien.Je mets une étoile car je ne n'ai pas le choix pour laisser un commentaire .
---

Colis arrivé dans un point relais en fermeture définitive ! Aucune nouvelle de ce colis , obligée d ’ appeler le service client , qui m ’ indique que mon colis est retourné chez eux et va repartir dans un autre point relais mais qu ’ on m ’ en informera par mail ! Aucun mail ! Aucun appel ! Aucune indication sur l ’ application ! Depuis le 18 novembre ! Un scandale !
---

Un colis incomplet sans avis du contenu ..... ils ne veulent rien savoir.Une arnaque , des voleurs .... ca me rassure , je ne suis pas la seule.Jamais je ne recommanderai ! ! ! ! ! !
---

Service client SHOROMMPRIVE totalement obsolète , qui ne réponds même pas aux demandes de ses clients ! J'ai entendu cette semaine sur RTL Julien COURBET intervenir pour une victime de SHOROOMPRIVE qui n'arrivait pas à se faire rembourser des commandes de matelas , dont 1 n'avait pas été livré ! Pour ce qui me concerne , idem pour 2 montres YONGER & BRESSON avec un vice caché !
---

Mon colis 172269317 a été livré le 7 juillet abimé . Showroomprivé a décidé de me remboursé 13,53€ sur 126€ . Jusque là pas de probleme . Sauf que nojs sommes le 20 aout et rien n a été fait . Le service comptable bloque . Ce sont des voleurs . Je suis ultra mécontente car ce n est pas comme si je ne les avais pas appelés 7 fois et laissé 5 mails ! ! Une honte
---

Une honte , le service client est inexistant.Mon colis devait être livré dans Paris , il a été livré à 1h20 dans un autre point relais sans me demander . Aucune réponse sur les réseaux sociaux , par e-mail ! ! ! ! ! À fuir en urgence
---

A plusieurs reprises mes commandes ont été livrés à un point relais different de celui que j'avais sélectionné.Le point relais est censée être le plus proche mais il se trouve à 30 minutes en voiture ou/et 45 minutes de transport ...
---

Je n ’ ai toujours pas reçu mon colis ! Le suivi annonce que celui à était livré Jeudi 06/05 alors que je ne l ’ ai toujours pas reçu ! Merci de m ’ indiquer comment procéder au remboursement ! Mme TURPIN
---

Malgré plusieurs contacts avec le service clientèle , il s'avère qu ' à plusieurs reprises des articles sont envoyés à une adresse de livraison totalement inconnue qui est visiblement inscrite dans les mails que je reçois de Bpost . Tous ces colis sont chaque fois renvoyés à l'expéditeur . Je ne reçois toujours rien . D'où sort cette adresse de livraison fantasque ? ? ? ? Avenue du port 28 à 1080 Bxl ? ? ?
---

Suite à un premier avis sur le site pour un colis non reçu et 3 mois d'échanges avec le service client , j'ai été recontactée par le service client . Ghizlane a été commerciale , compréhensive et réactive , le montant du colis a été totalement remboursé . Je trouve ça dommage qu'il faille passer par un avis sur un site pour être entendue .
---

Je n ait pas eut car suis allée le chercher trop tard il est repartit chez vous J attend le remboursement Merci
---

Pour la deuxième fois , une de mes commande a été annulé , la 1ère fois c ’ était Sur des bottines MJus , j ’ ai appris le jour où je devais les recevoir que ma commande était annulé , j ’ ai écris au service client par mail Qui n ’ a jamais prit la peine de me répondre . Et cette fois le soir ou ma commande a été livré qu ’ il n ’ y avait pas un article ( merci je m ’ en été aperçu ) .Le service client est à revoir ..
---

Vous m'avez livré une robe que je n'ai pas commandé , je parle de la livraison du 18 ou 19 février . Vous vous êtes trompé d'article . J'ai voulu le signaler en ligne mais à chaque fois on me dit que le service retour/ réclamation est indispensable sur votre site . Je suis très déçue . J'attends votre retour , il s'agit de la robe en carreaux de Vichy de couleur noir et blanc .
---

Livraison de commande elle a pas été effectué comme quoi adresse inconnue malgré que j ’ ai effectué plusieurs commandes et que j ’ ai jamais vu le problème de livraison très mécontente
---


In [ ]:
# Regroupement des topics
qualite_produit_topics = {3, 6, 18, 19, 23, 29}
livraison_topics = {5, 10, 24, 26, 27}
service_client_topics = {7, 8, 13, 14, 28}

df['label'] = np.nan

df.loc[df['topic_id'].isin(qualite_produit_topics), 'label'] = 0
df.loc[df['topic_id'].isin(livraison_topics), 'label'] = 1
df.loc[df['topic_id'].isin(service_client_topics), 'label'] = 2

df['label'] = df['label'].astype('Int64')  # int nullable
df['label'].value_counts(dropna=False)

label
<NA>    6191
0       4732
1       2374
2       1793
Name: count, dtype: Int64

Batches:   0%|          | 0/223 [00:00<?, ?it/s]

Batches:   0%|          | 0/56 [00:00<?, ?it/s]

LogisticRegression(class_weight='balanced', max_iter=2000)

              precision    recall  f1-score   support

         0.0      0.953     0.864     0.906       946
         1.0      0.796     0.819     0.807       475
         2.0      0.756     0.914     0.827       359

    accuracy                          0.862      1780
   macro avg      0.835     0.865     0.847      1780
weighted avg      0.871     0.862     0.864      1780

Classe prédite  0.0  1.0  2.0
Classe réelle
0               817   76   53
1                33  389   53
2                 7   24  328

,text,label_true,label_pred,correct
1,j'ai du leurs écrire pendant 2 mois pour me faire rembourser et en plis je n'ai reçu que la moitié . je n'ai jamais reçu ma commande et le service client vous prends pour des… je ne sais même pas s'il s'agit de réels personnes . je ne commanderai plus jamais .,0,2.0,False
3,sur 5 commande jai eu 3 problèmes soit produit manquant soit apres 2 mois d'attente 2 jours avant la livraison ma commande a etait annulé ... ou reception d'un autre article qui n'était pas le mien ... j'hésite a recommander ...,0,1.0,False
6,erreur de livraison . pieces manquantes . colis incomplet .,0,1.0,False
8,j ’ attends depuis des semaines le remboursement de 2 articles retournés ....,0,2.0,False
21,"commande livrée très vite ce qui est très agréable , car bien souvent les délais sont trop longs",0,1.0,False
39,"une catastrophe , le colis est arrivé ouvert et en mauvais état . les produits avaient fuit et étaient a même le carton . une honte .",1,0.0,False
40,"des années que je commande sur veepee et toujours au top . quand je commande chez eux je n'ai jamais été déçu , ils ne se trompent pas dans l'article comme shorommprive trois fois ils se sont trompé de commande . je reçois la plupart toujours à l'avance mais rarement en retard . merci",0,2.0,False
41,une commande passée il y a 4mois . je viens tout juste de recevoir un mail pour me dire que je vais être remboursé et qu ’ ils n ’ allaient pas me livrer ... un service déplorable . je déconseille fortement .,1,2.0,False
44,"commande effectuée le 17 décembre , soit disant expédiée le 20 . j ’ ai contacté le service client par e-mail et j ’ ai eu la chance d ’ obtenir une réponse type « ils effectuent des recherches et me tiennent au courant » . aujourd ’ hui , 2 janvier , aucune nouvelle de mon colis . mon compte en banque a bien sûr été débité depuis longtemps . je extrêmement déçue par l ’ évolution de ce site de vente en ligne .",1,2.0,False
50,"retard sur la livraison mais assez satisfaite sur le produit . seul regret , j ’ aurai du commander taille 54 au lieu de 52",0,1.0,False
52,je ne peux me permettre de juger le service client car je n ’ ai pas encore eu besoin d ’ avoir à faire avec eux cordialement,0,2.0,False
65,livraison avant la date prévue . petite déception sur le tableau qui n ' a pas autant de touches de doré que sur l'image du site .,0,1.0,False
67,"boite à pain cassé dans le colis pas assez protégé dommage pour moi car elle me plaisait beaucoup et le retour est a ma charge alors que je n ' y suis pour rien ? je ne comprends pas qu'il n ' y es pas un échange , ?",1,0.0,False
70,"j'ai fait 4 retours , pas de remboursement . un article n ' a pas été livré , pas de remboursement non plus ! ils ne remboursent plus rien . a fuir ! ! !",0,2.0,False
75,"incompétence et mauvaise foi ! showroomprive ne respecte pas les termes du contrat infinity ! certains articles , alors qu'ils sont désignés comme faisant partie d ela livraison gratuite n'en bénéficient pas , selon l'humeur de showroomprivé ! je déconseille fortement ce site , je n'ai eu que des problèmes !",0,2.0,False
90,"voilà depuis ma commande du 16 décembre , j'attends de recevoir un reconditionné d'une valeur de 659€ frais de port compris , qui est soit disant en traitement dans leur plateforme logistique et donc prêt à être envoyé . avec une estimation de livraison entre le 27 et 29 décembre . on est le 7 janvier toujours rien reçu , pas de réponse à mes mails , du coup je souhaite annuler la commande mais impossible sur le site . donc je vais les harceler au pour récupérer mon argent ce qui est déjà de trop .je ne compte pas en rester là mais je vais faire tout ce qui est possibles pour faire fermer cette boîte juridiquement parlant et quel ne puisse plus jamais nuire au consommateur .",1,2.0,False
92,"3 commandes passées , 3 commandes annulées à peine une semaine avant ladite livraison.pas de raison invoquée , je supprime l ’ application et commande désormais sur d ’ autres sites plus fiables .",0,1.0,False
94,"je suis tres mecontent de ce site j ’ ai commandé un lit nightandmore en 200x200 ( et matelas ) vu la taille , il y avait deux lors de la livraison ce jour , jai bien recu les deux et le matelas mais a ma grande surprise seulement 4pieds au lieu de 8 . j ’ ai donc refuser la commande . sauf que comme j ’ avais pris mes dispositions pour mon anciens lit . je ne l ’ ai plus . je me retrouver donc avec rien pour dormir . la solution de votre groupe de m e r d e , repasser commande lol mais surtout aucune solution j ’ attend donc d ’ etre recontacter dans les plus brefs delai afin que vous me trouviez une solution car meme si je recommande un lit qui me convienne , les delai de livraison sont tels que je vais rester 1 , 2 voir plusieurs mois sans lit . je vous demande donc de prendre en consideration cela et de me recontacter avec une vrai solution",2,0.0,False
112,"je donne une étoile car je ne peux pas mettre moins . jusqu ' à présent je commandais pas mal sur vente-privé malgré les frais de livraison de 6,50€ sur quasiment toutes les ventes qui freinent l'achat ( heureusement pour mon compte en banque ) . j'ai fais une commande début juillet , la livraison était prévue entre le 31/07/2017 et le 05/08/2017 . a ce jour m ' a commande n ' a toujours pas été expédié , je n'ai eu aucune explication . j'ai essayé de les contacter à plusieurs reprises , sans nouvelle de leur part et le pire c'est que je peux même pas annuler ma commander car le fournisseur à déjà expédié ma commande et se trouve actuellement dans l'entrepôt de vente-privée . qu'est ce qui les empêche donc de me la faire parvenir ? en conclusion je ne recommanderai absolument pas ce site de vente en ligne.suite de l'épisode : après avoir posté ce commentaire ils m'ont informé que ma commande ne sera pas livré . j'ai donc été remboursé . 1 mois d'attente pour avoir un produit qui au final n'arrivera jamais .",1,2.0,False
113,il manque 90 % de ma commande et je n'ai pas d'infos sur le fait de la recevoir ou non en totalité un jour .,0,1.0,False