In [1]:
import pickle
import os
import numpy as np
import pandas as pd

from contextualized_topic_models.utils.data_preparation import TopicModelDataPreparation
from contextualized_topic_models.models.ctm import CombinedTM
from sentence_transformers import SentenceTransformer

In [ ]:
# obligé de reprendre les données ici car bert n'a pas été entrainé sur dataset_final.pkl, donc j'avais un problème de matching entre les embeddings et les textes
df = pd.read_csv("../data/preprocessed/reviews_trust_clean.csv")
df_sans_contexte = pd.read_csv("../data/preprocessed/reviews_trust_clean_stopwords_supprimer.csv")

# on retire quelques stopwords supplémentaires
stopwords_custom = {
    'montre', 'montres', 'boucle', 'boucles', 'oreilles', 'oreille', 'paire', 'paires', 'lunettes', 'bracelet', 'bracelets', 'collier', 'iphone', 'téléphone', 'pendentif', 'robot', 'robots', 'aspirateur', 'baskets', 'basket', 'chaussure', 'chaussures', 'sandales', 'plantes', 'plante', 'arbres', 'arbre', 'bulbes', 'willemse', 'sommiers', 'jardin', 'bague', 'lampe', 'lampes', 'abat-jour', 'abat jour', 'lampadaire', 'parfum', 'shampoing', 'shampooing', 'shampooings', 'cheveux', 'masque', 'masques', 'crème', 'élastiques', 'manteau', 'bougie', 'cadre', 'écouteurs', 'vélo', 'robe', 'vêtements', 'bijoux', 'sac', 'portable', 'clio', 'luminaire', 'oreillette', 'induction', 'écouteur', 'couette', 'samsung', 'téléphones', 'smartcase', 'abat', 'apple', 'watch', 'shirt', 'tee', 'chemise', 'shirts', 'hortensias', 'orchidée', 'sacs', 'plant', 'chaises', 'lacoste', 'polo', 'pantalon', 'jean', 'jeans', 'sneakers', 'lunette', 'écran', 'tablette', 'tablettes', 'table', 'tables', 'chemisier', 'pulls', 'pull', 'trotinettes', 'trotinette', 'chaussons', 'chausson', 'brosse', 'brosses', 'crèmes', 'gel', 'gels', 'parfums', 'robe', 'robes', 'sacoches', 'sacoche', 'vestes', 'veste'
}

def clean_custom(text):
    tokens = text.lower().split()
    tokens = [t for t in tokens if t not in stopwords_custom]
    return " ".join(tokens)

df_sans_contexte["clean_comment"] = df_sans_contexte["clean_comment"].apply(clean_custom)
df["clean_comment"] = df["clean_comment"].apply(clean_custom)

texts_sans_contexte = df_sans_contexte["clean_comment"].astype(str).tolist()
texts_avec_contexte = df["clean_comment"]

# Si on modifie encore les stopwords et qu'on veut regénérer les embeddings, décommentez le code ci-dessous
# --------- Pour regénerer les embeddings, décommentez le code ci-dessous ---------
# model = SentenceTransformer('dangvantuan/french-document-embedding', trust_remote_code=True)
# X_ctx = model.encode(
#     texts_avec_contexte,
#     batch_size=32,
#     show_progress_bar=True
# )
# with open("../data/embeddings/emb_sbert_fr_ctm.pkl", "wb") as f:
#     pickle.dump(X_ctx, f)

# --------- Pour regénerer les embeddings, décommentez le code ci-dessus ---------

with open("../data/embeddings/emb_sbert_fr_ctm.pkl", "rb") as f:
    X_ctx = pickle.load(f)
    
X_ctx = np.asarray(X_ctx)
assert X_ctx.shape[0] == len(texts_avec_contexte), "Mismatch nb docs vs nb embeddings"

In [9]:
tp = TopicModelDataPreparation("camembert-base")

training_dataset = tp.fit(
    text_for_contextual=texts_avec_contexte,
    text_for_bow=texts_sans_contexte,
    custom_embeddings=X_ctx
)

bow_size = len(tp.vocab)
ctx_size = X_ctx.shape[1]
bow_size, ctx_size

(20667, 768)

In [10]:
K = 30 # nombre de topics
ctm = CombinedTM(
    bow_size=bow_size,
    contextual_size=ctx_size,
    n_components=K,
    num_epochs=20,
    num_data_loader_workers=0
)

ctm.fit(training_dataset) # entraînement

Epoch: [20/20]	 Seen Samples: [300800/301800]	Train Loss: 229.82593760388963	Time: 0:00:04.179370: : 20it [01:24,  4.21s/it]
100%|██████████| 236/236 [00:02<00:00, 83.56it/s]

In [11]:
topics_words = ctm.get_topic_lists(20)  #  le nombre de mots à afficher par topic
for k, words in enumerate(topics_words):
    print(f"Topic {k}: {', '.join(words)}")

Topic 0: prix, frais, trouve, marque, produits, autres, moins, marques, port, acheter, sites, ventes, cher, ailleurs, parfois, souvent, affichés, 50, pense, disant
Topic 1: falloir, gain, obligation, courage, réceptionnés, suit, commencent, revenu, penser, plaindre, premiere, chargé, trouvent, manifestement, lecture, écrans, buffet, cinq, compensation, sérieusement
Topic 2: tenté, aimé, pensent, obligation, bye, réponde, croix, apercevoir, apparaît, venant, requête, impose, osent, feront, surement, envoyant, revenu, trouvent, oblige, falloir
Topic 3: commandé, déçue, article, déception, bonjour, reçu, déçu, première, commandés, étiquette, articles, renvoyer, comment, erreur, retourner, modèle, moment, cadeau, mauvais, celle
Topic 4: rapide, rapidement, tôt, avance, bonne, emballé, satisfaite, super, rapidité, excellent, prévue, très, emballés, rapport, présentation, prévu, recommande, qualité, produit, date
Topic 5: long, longue, délai, délais, delai, peu, longs, crise, respecté, sanitaire, marchandise, respectés, trop, longues, livraison, sinon, marchandises, tardive, delais, correct
Topic 6: commanderai, retourner, article, erreur, renvoyer, totalité, lamentable, première, absolument, erreurs, commandés, comment, pire, retours, incomplète, défectueux, renvoie, charge, nul, recevoir
Topic 7: réponse, service, veepee, client, aucun, arnaque, mois, depuis, clients, aucune, rembourser, argent, jamais, fuir, honte, mails, problème, showroom, acheté, cliente
Topic 8: ai, remboursement, mois, plus, commande, fois, après, service, veepee, faire, fait, depuis, qu, rien, jamais, être, autre, est, mail, compte
Topic 9: revenu, réceptionnés, mépris, précisant, falloir, capacité, pensent, furieuse, granjon, enrichir, battre, parlant, membre, commencent, manger, croix, suivante, ps, quinzaine, parlent
Topic 10: toujours, passée, 12, livré, 15, livrée, aucune, jours, dernière, retard, attendre, 2020, juillet, 20, perdu, juin, commande, entre, hui, recevoir
Topic 11: falloir, tenté, pensent, cinq, milieu, dix, combien, gardez, concerné, bye, valide, comprennent, bénéficie, dyson, leçon, vent, fassent, croyez, commerçants, finit
Topic 12: conformes, conforme, description, rapide, attentes, avance, prévu, emballée, descriptif, produit, réceptionnés, parfait, suivis, tôt, prévue, ultra, pensent, correspondant, falloir, gain
Topic 13: aucune, mails, réponse, malgré, depuis, aucun, toujours, attends, remboursement, fuir, veepee, répond, appels, ni, mois, rembourser, semaines, sav, clients, honte
Topic 14: commande, colis, jours, mail, toujours, remboursement, rien, demande, après, service, faire, réponse, être, livraison, cette, problème, jamais, client, plus, ai
Topic 15: cliente, arnaque, ventes, années, livraisons, retours, problèmes, site, avis, commandes, moins, sites, prix, frais, voir, surtout, souvent, attention, autres, ans
Topic 16: site, plus, retour, frais, est, non, vente, si, tout, euros, commandes, bien, car, faire, marque, achat, ai, articles, fois, alors
Topic 17: furieuse, mari, merci, adore, combien, pauvre, falloir, penser, racheter, agir, parlons, série, pensent, réaction, appui, réalisé, droits, parlent, commerçants, gardez
Topic 18: recu, abîmé, cassée, cassé, manquait, verre, bidons, déchiré, ouverture, manquante, carton, système, chance, cassés, contenu, jeté, ouvert, verres, appareil, rayures
Topic 19: taille, petit, tailles, grand, photo, petite, correspondent, 40, tissu, déçu, 42, 38, déçue, couleur, xl, grande, trop, grandes, couleurs, haut
Topic 20: ai, est, plus, retour, qu, vente, site, tout, donc, si, une, frais, euros, articles, privée, car, faire, après, produit, reçu
Topic 21: contente, merci, satisfaite, belles, plaisir, remercie, lu, superbes, tjrs, fidélité, commencent, inquiéter, détail, venant, constater, rend, jolie, buffet, imaginaire, yeux
Topic 22: éventré, manquante, oublier, refus, enlever, écrasé, verre, lessive, contenu, volé, casser, cassées, comptent, complète, connecter, éclaté, marche, fermoir, mains, mobile
Topic 23: petit, taillent, matière, couleur, taille, petite, tailles, grand, tissu, photo, grande, 36, commandées, tissus, petits, pensais, déçue, correspond, maillot, mauvaises
Topic 24: ouvert, livreur, poste, point, domicile, état, emballage, arrivé, carton, relais, aller, boîte, récupérer, lettres, dû, chercher, choisi, heureusement, abîmé, colis
Topic 25: revenu, falloir, pensent, figure, derniere, droits, conforme, trésorerie, parfait, suivante, gain, arrivant, pleurer, littéralement, ancien, foutage, plaque, commandent, titre, dénoncer
Topic 26: delai, delais, retardée, respecter, ras, duré, pr, respecté, chef, intégralité, 1mois, ment, commencent, long, derniere, jms, manquerai, honteuse, banquette, bda
Topic 27: commande, colis, livraison, être, chez, avoir, après, mois, commandes, fois, vente, rien, jours, qu, est, fait, il, ai, plus, service
Topic 28: ai, qu, remboursement, commande, plus, est, service, colis, client, chez, vente, après, donc, jours, être, faire, retour, fait, rien, avoir
Topic 29: qualité, rapport, belle, bonne, irl, très, beaux, recommande, collection, bel, beau, intéressant, jolies, jolis, choix, agréables, bonnes, attractif, compétitifs, achetés

In [12]:
doc_topic = ctm.get_doc_topic_distribution(training_dataset)  # shape (n_docs, K)
df["topic_id"] = np.argmax(doc_topic, axis=1)
df["topic_confidence"] = doc_topic.max(axis=1)

100%|██████████| 236/236 [00:02<00:00, 83.52it/s]

In [13]:
os.makedirs("./artifacts/ctm", exist_ok=True)
os.makedirs("./artifacts/ctm/exports", exist_ok=True)

# ctm.save(models_dir="./artifacts/ctm/model")

# with open("./artifacts/ctm/vocab.pkl", "wb") as f:
#     pickle.dump(tp.vocab, f)

pd.DataFrame({
    "topic_id": np.arange(len(topics_words)),
    "top_words": [", ".join(w) for w in topics_words]
}).to_csv("./artifacts/ctm/exports/topics_top_words.csv", index=False)

np.save("./artifacts/ctm/exports/doc_topic.npy", doc_topic)

df.to_csv("./artifacts/ctm/exports/reviews_with_topics.csv", index=False)

In [14]:
topic_counts = df["topic_id"].value_counts().sort_index()
display(topic_counts)

topic_id
0     456
1     262
2     421
3     677
4     615
5     812
6     770
7     624
8     317
9     276
10    647
11    245
12    621
13    690
14    109
15    587
16    292
17    615
18    702
19    950
20    146
21    617
22    696
23    725
24    543
25    342
26    231
27    141
28     53
29    908
Name: count, dtype: int64

In [27]:
def examples_for_topic(t, n=5):
    return df[df["topic_id"]==t]["clean_comment"].head(n).tolist()

for t in range(K):
    ex = examples_for_topic(t, 3)
    print(f"\n=== Topic {t} ===")
    for e in ex:
        print("-", e[:200])

=== Topic 0 ===
- commande passée pour une vente , livraison 15 nous après la date prévue , déjà 6 semaines après l'achat , sur 3 produits , 2 manquants . pas pro , pas sérieux , aucun geste commercial hormis le rembou
- annulation de commande après 2 mois d ’ attente dans un geste et sans explication . retard de livraison et report à 3 reprise pour se résultat incompréhensible et inadmissible je recommande pas le sit
- bonjour , commande fait sur showroom n° 233332467 avec un point relais défini . cette commande a été déviée de son point d'origine de plus de 6km par le bon vouloir du transporteur ? ? réponse de show

=== Topic 1 ===
- j'ai fait la commande d'une sacoche et d'un pull , il y a de ça 1 mois et demi , déjà le temps d'attente est énorme , mais en sois ce n'est pas si grave.par contre sur mon colis à 120 euros , je n'ai
- j'ai commandé des tapis il y a deux mois , livrables début mai . début mai problèmes techniques , retard dans le traitement chez showroom . puis livraison prévue le 18 mai . les colis sont arrivé chez
- commande 1/01/2021 - livraison prévue le 4/02après avoir contacté showroom par tél 22/02 je reçois en retour un mail le 24/02 un mail m'annonçant l'ouverture d'une enquête et qu'ils me tiendraient au

=== Topic 2 ===
- extrêmement deçu pour mes achats lors la vente dolores promesas , j'ai reçu des vetements sales et déja utilisées !
- 1 mois et demi d ’ attente pour recevoir des mauvais articles .
- j'ai commandé une qui n ' a jamais fonctionné le 21 mars 2021 a ce jour toujours pas solutionner a évité comme site .

=== Topic 3 ===
- facture les frais d'expédition pour chaque livraison partielle . soyez gentils et laisser le choix au client . merci d'avance
- tres bon site . produits pas chers , livraison rapide .
- très bon site . je recommande .

=== Topic 4 ===
- lit coffre commandé sur showroomprivé reçu une semaine avant la date prévue . bonne expérience même si le produit n'est pas d'une grande qualité . montage sans problème avec notice fournie .
- 100 % , satisfaite ! produits toujours conformes à ce que j'avais commandé , je ne prends que des marques connues et je n'ai jamais été déçue . livraison au top au relais colis .
- ca fait tellement bizzare voir des avis différents . je viens de recevoir ma première commande , en une semaine seulement . des au top qualité . a voir les prochaines commandes .

=== Topic 5 ===
- sav desoeuvrant ! ! une prestataire livraison déplorable ! quand on reçoit tout va bienquand on reçoit rien , c ’ est affreux ! ! ! attention ! ! !
- problème toujours pas réglé . quelle honte.commande 226762173merci de nous contacter d ici a lundi soir
- plusieurs commandes jamais de problème .

=== Topic 6 ===
- commande etat a+ . livraison d un vieux pourri sans batterie rayé partout et inaudible ! ! ! super l affaire 300 euros a la poubelle merci showroomprivee ! ! ! passez votre chemin ils sont nuls et ne
- extrêmement déçue de la vente ! ! achat d ’ un reconditionné grade a+ ( fournisseur prs , phone recycle ) il a fonctionné 15 jours ! ! ! sav lamentable jusqu ’ a 6 jours pour répondre à une ’ question
- ce sont des voleurs . showroomprivé vend des ipad reconditionnés en mauvais état . ils rejettent la faute sur leurs fournisseurs mais vous laisse vous démerder avec eux . soit disant ils doivent appel

=== Topic 7 ===
- j'ai commandé des mules de la marque moosefield , très déçue du produit , une étiquette collée sur une des mules donc tâche ! ! produit très moyen .
- je vous remercie pour votre retour . aujourd'hui je viens de recevoir le reste de ma commande . c'est donc la faute de la poste qui a mal fait son travail .
- commande perla isla 75 euros de le et le ne correspondent pas du tout à ce que j ai commander les perles ne me plaisent pas du tout je ne recommande pas du tout cette marque .. déçue

=== Topic 8 ===
- je suis bluffée par le service client : pas d'attente au , réponse claire , remboursement rapide . cela me donne confiance , j ' y retournerai .
- ne mérite meme pas une etoile beaucoup de daube ! ! ! !
- très réactifs après litige .

=== Topic 9 ===
- arnaque j ’ ai acheté une combinaison blanche à 33€ au lieu de soit disant 100€ , que j ’ ai reçu + d ’ un mois après , avec des traces noires sur le bas de la combi et surtout elle était super transp
- showroom s'est trompé dans l'envoi de ma commande pour une montre.je n'ai pas reçu l'article commandé.mais pour le retour , je dois payer l'affranchissement l'erreur est de leur côté . le retour devra
- je profite d'une vente eastpak pour changer le de ma fille qui vient de nous lâcher.je choisis un modèle out of office que je connais bien puisque ses 2 soeurs en ont un , et elle le choisit de couleu

=== Topic 10 ===
- produits provenant de chine , contrefaçon aucune qualité.première et dernière commande ! ! ! !
- profitez de 12€ de réduction en entrant le code pauack9f lors de l ’ inscription
- décevant ! ! ne pas commander !

=== Topic 11 ===
- première expérience et tous c ’ est très bien passer .mes scandinaves impeccable .livraison au top
- parfait ! livraison super rapide , moins d ’ une semaine après avoir passé la commande ! !
- ce site est correct respecte les délais et les produits sont de qualité

=== Topic 12 ===
- 2 robes achetées sur showroom privées , une pour ma fille , une pour moi . ma fille me dit qu'il y a un trou , donc je regarde du coup les deux robes : toutes les deux défectueuses ( trou au niveau de
- à fuir showroomprive en cas de problème service client déplorable nul et j'en passe j'ai passé une commande le 5 mai 2021 sur une vente je reçois un mail m'informant que la livraison va être retardé a
- j'ai toujours été cliente chez showroom , jamais déçue . il y a quelques jours , je reçois un article non conforme . on m'envoie le bon retour . je dois faire l'avance des frais , hors de question , o

=== Topic 13 ===
- vente article manquant photo prise sur 6 articles la moitié livrée sans explication manque de respect.numero de commande 230130353
- colis non conforme à la commande . sav incompétent et retour impossible à partir d ’ un smartphone . passez votre chemin…
- de marque le s'est décollé le premier jour bizarre et on ne veut pas me le rembourser . mauvaise expérience

=== Topic 14 ===
- bonjour , ca doit faire 5 ans environ que je suis membre showrooprive . je n ’ ai jamais eu de soucis en particulier à part 2/3 petites bricoles…par contre depuis ces 3 derniers mois , une vraie catas
- vente honteuse , article erroné , article manquant , pas de bon de livraison , retard et service client désastreux.après deux appels désastreux , je tenais à avertir les plus courageux qui oseront com
- s'il y'avait une option : ne pas mettre d'étoile ( une étoile c'est trop ! ) je serais contente . j'ai passé une commande mi-avril et là nous sommes en mi-juin je ne l'ai toujours pas reçu ! et quand

In [28]:
#Évaluer la diversité des topics
def topic_diversity(topic_words):
    """
    Calculate topic diversity: proportion of unique words among top words of all topics.
    topic_words : list of lists, each sublist contains the top words of a topic.
    """
    top_words = []
    for words in topic_words:
        top_words.extend(words)

    unique_words = set(top_words)
    diversity = len(unique_words) / len(top_words)
    return diversity
diversity_score = topic_diversity(topics_words)

print(f"Diversité des topics: {diversity_score:.2f}") # closer to 1 : each topic uses unique words(good diversity)

Diversité des topics: 0.77

In [29]:
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora import Dictionary

# texts : liste de documents, chaque document = liste de tokens
# topic_words : liste de listes des mots top de chaque topic
texts = df_sans_contexte["clean_comment"].apply(lambda x: x.split()).tolist()
dictionary = Dictionary(texts)

cm = CoherenceModel(
    topics=topics_words,
    texts=texts,
    dictionary=dictionary,
    coherence='c_v'
)

coherence_score = cm.get_coherence()

print("Score de cohérence:", coherence_score)

Score de cohérence: 0.5348584450118433

In [31]:
for c in df[df["topic_id"] == 0]["Commentaire"]:
    print(c, "\n---\n")

Commande passée pour une vente Lacoste , livraison 15 nous après la date prévue , déjà 6 semaines après l'achat , sur 3 produits , 2 manquants . Pas pro , pas sérieux , aucun geste commercial hormis le remboursement promis des 2 articles manquants .
---

Annulation de commande après 2 mois d ’ attente dans un geste et sans explication . Retard de livraison et report à 3 reprise pour se résultat incompréhensible et inadmissible je recommande pas le site mieux vaut aller sur vente privée au mon d on attend mais on a sa commande
---

Bonjour , Commande fait sur Showroom n° 233332467 avec un point relais défini . Cette commande a été déviée de son point d'origine de plus de 6Km par le bon vouloir du transporteur ? ? Réponse de Showroom n'allez pas le chercher et on vous remboursera ? ? Quelle est l'interré de commander d'attendre plus d'un mois pour le remboursement . Sur Amazon l'ecoute et le respect du client est leur priorité.Merci de prendre exemple
---

Pour commander il n ' y a pas de problème mais POUR LES RETOURS c'est très compliqué , l'article étant défectueux.Les conseillers n'écoutent pas et répétent toujours pareils . Je suis très déçue et hésiterais désormais à commander par ce site.Surtout que j'attends aussi ma commande LACOSTE , qui était prévue pour la fête des pères et qui est encore repoussée . Commande passée le 5 Mai 2021je trouve que c'est un peu exagéré comme délai .
---

Achete une pergola sur shorom vendu par SOURCIDYS A TOURS paye 37 € de frais de livraison .Il y avait 3 colis j en ai reçu 2 , il me manque le 3 ème qui contient les pieds .. Depuis le 10 juin pas de nouvelles , la société ne répond pas ... ni a moi ni a shorom .Du coup impossible de la monter paye 299 euros pour rien ..... site à banir.Shorom a de suite pris la réclamation en compte mais rien bouge .
---

Ne répondent pas aux mails de réclamation malgré relance.Suite au message sur Truspilot me laissent un message , toujours sur Truspilot , m'indiquant qu'ils vont me contacter ... j'attends encore ... j'ai à nouveau relancé par mail et par téléphone et je suis supposée avoir reçu un mail le 15 juin dernier . Rien dans ma boîte de réception , rien en spam ... bonnes gens , fuyez !
---

Un service clients épouvantable et malhonnête . J ’ ai refusé un colis déchiré et contenant des tasses cassées , et Showroomprivé refuse de me rembourser car le transporteur a noté le colis comme livré . Ils m ’ ont fait croire à une enquête auprès du transporteur qui aurait duré 15 jours selon eux , pour finalement me répondre « votre colis vous a été livré » . Je viens de leur écrire car les téléphonistes sont lamentables , mais je ne me fais pas d ’ illusions . Pour moi Showroomprivé c ’ est terminé , et pourtant j ’ ai beaucoup acheté sur ce site et depuis des années . Je n ’ accepte pas de me faire voler comme ça .
---

Très déçue ! J ’ ai souvent commandé sur showroom privé , toujours livrée rapidement.Je commande un maillot de bain le 23/05 , je reçois un message m ’ informant d ’ un retard de livraison - maintenant annoncée le 21/06 ... jour de mon départ en vacances ... aucun numéro de suivi mondial relay donc impossible de savoir où est mon colis ... Commande 231658244
---

Voleur , escroc ! ! ! ! ! Très mauvaise expériencelivraison reçu à moitié après avoir contacté le service client aucune réponse ... aucun dédommagement ! Dédouanement en rejettant la faute sur le fournisseur qui est injoignable ! ! Un scandale ! A fuir ! ! !
---

Ça fait un mois que ma commande aurait du être livré et Showroom fait traîner l ’ affaire malgré mes appels et messages Pourtant Chronopost m ’ a indiqué le colis comme perdu
---

Cliente depuis des années , déception totale . J ai reçu un colis endommagé , il manquait un produit ( petite valeur ) 3 semaines d'investigation obligatoires , je reçois un mail me disant que la commande était bien livrée mauvaise réponse de leur part . Je quitte leur fichier client . De plus les retours sont payants .
---

Bonjour , J'ai réservé un voyage pour l'Egypte sur le site de Showroom . ils ont bien débités l'argent . La 1er fois le voyage a été annulé par l'opérateur Travel Evasion d'après eux , j'ai du reporter mes vacances . La 2eme de nouveau annuler , avec aucunes explications ni par phone , ni par mail . Mon départ était prévu pour le 19 juin 2021 , j'apprends avant - 10 jours que mon voyage est encore annulé , je ne comprends pas pourquoi étant donné que l'Egypte est ouvert aux touristiques . Travaillant à l'aéroport plusieurs personnes s ' y rendent . Attention , je vous conseille de faire attention avec ce site , ils travaillent avec notre argent pendant ce temps . Vous appelez le site et malheureusement les personnes aux bouts du fils ne sont pas en mesure de vous répondre , de plus personne ne vous rappel également .
---

Avant de passer commande sur ce site j'ai voulu voir les avis le concernant et j'ai bien fait , en parcourant ce topic je remarque qu'il y ' a plus de négatif que des clients satisfaits , en plus les réponses du service client sont des réponses types , de Mr Ayoub , et rien ne dit que les plaintes des clients on été résolus , je vais voir ailleurs .
---

Nul de chez nul , plusieurs commandes passées , après plusieurs mois d'attente , l'article arrive et ce n'est pas le bon . Et ça pour 4 commande entre août 2020 et juin 2021 . A fuir absolument , perte de temps.Même s'il vous rembourse dans les frais d'envoi qu'il ne rembourse pas le mal . Incompétent .
---

J ’ ai passée une commande hier soir pour un lot de 3 valise , tous s ’ est bien passé jusqu ’ au niveau de valider l ’ opération avec ma banque . Une fois la validation est faites au niveau de la banque le site me redirige vers l ’ application ShowroomPrivé en me disant que ma « commande a bien été enregistré sous le numéro suivant » sauf que aucun numéro de commande n ’ apparaît et je n ’ ai pas reçu de mail de confirmation pour ma commande . Je suis enceinte et j ’ ai besoin d ’ une valise . J ’ espère vraiment pas être prélevé car j ’ ai pas de numéro de commande ni un mail de confirmation .
---

Des gens au téléphone incompétents qui s ’ excusent mais ne règlent aucun problème vaisselle très mal emballé expédié par la poste du jamais vu de la vaisselle par la poste … .. vaisselle cassée aucun recours showroomprive refuse de me renvoyer une assiette cassée et 2 ébréchées il me propose 10 euros en dédommagement or j ’ ai commandé un service complet et ces assiettes manquantes pénalisent mon service Donc je vous déconseille fortement ce site car des amis ont également eu de gros problèmes avec eux
---

J'ai deux commandes en cours , la première n'est jamais arrivée entière . Depuis l'enlèvement du colis je suis toujours en attente de mon remboursement . Pour la seconde commande , on m ' a prévenu qu'il ne savait pas où était tous les colis . Fuyez , je ne sais pas quoi faire .
---

Suite à un avis négatif publié le 17 mai un conseiller devait me recontacter ( message du 18mai ) J'attends toujours.J'attends toujours aussi mon remboursement .... Le service de préparation des commandes est nul ( 2 erreurs en 2commandes ) Et le service client aussi . Car ils n ont vraiment rien fait pour réparer leurs erreurs . Aucun geste commercial et ils ne se dépêchent pas non plus pour rembourser.Vivement que je récupère mon argent pour que je puisse enfin fermer mon compte
---

J avais publié un avis tres négatif concernant showroom privé il y a quelques jours . Suite a ça une personne de ce site m a contacté pour connaître le problème . Cette personne a été tres agréable et a répondu à mes attentes . Je voulais signaler celà aussi . C est bien de le dire quand c est mauvais mais aussi quand c est bien .
---

Une commande effectuer le 11 Avril , reçus le 23 Avril . J'ai commandé une table ( beige ) et je reçois deux coloris different ( beige et gris ) donc mauvais articles.Je demande un retour de la commane et un remboursement depuis le 24 Avril.Nous sommes le 30 Mai et le service ne me propose toujours aucune solution hormis de conservé ma commande .... et un remboursement se moitié ... Le service est déplorables et ne respecte pas le délais de réponse dit.Trés déçus de la qualité de service après vente ! ! !
---

BjrAchat d ’ un trampoline il y a un mois1 colis reçu sur 31 retourné à l ’ expéditeur et 1 autre en instance ds l ’ agence de DPD depuis 4 semaines Je contacte le SAV de Showroom à 5 reprises sur cette et rien ne se passe J ’ ai un colis qui m ’ encombre chez moi et je n ’ ai pas été remboursé Mes enfants attendent avec impatience ce trampoline qui n ’ arrivera jamais ...
---

Très très déçu du site car commande passée le 5mai 2021 et date de livraison le 12 mai 2021 . Aucune commande reçu le 12 mai et pas un e-mail ou sms du site pour dire qu ’ il y a un retard sur la livraison . Donc ils font le mort . Livraison le 26 mai 2021 et appel pour le service client pour comprendre le pourquoi du comment de leur silence … . Aucune réponse juste DÉSOLÉ ! ! ! ! Pas d ’ explication sur le retard , rien… . Bizarre quand même . Je m ’ attendais à un geste commercial pour me dédommager du préjudice et là… que dalle juste un pauvre désolé . C ’ est minable voire pitoyable… . Vraiment déçu du site…😤😤😤👎👎👎
---

Bonjour a tous , Très mauvaise expérience sur ce site.Ma commande a été validée 3 fois malgré les `` pass securité '' bancaires . En effet le site ne vous indique pas de suite que votre commande est validée du coup vous ne savez pas si elle est prise en compte ou pas.J'appelle ensuite le service client qui me fait patienter une éternité pour finalement me raccrocher au nez.Insupportable !
---

J ai renvoyé un colis qui est arrivé cassé ( meuble tv ) cela fait 5 mois que j attends le remboursement sans nouvelles de leur part .... très déçu ! En + On me dit qu ’ il n est plus dispo alors que il est toujours en vente sur le site ..... ! ! ! !
---

J ’ avais l ’ habitude de commander Showroomprive aujourd ’ hui je suis déçue ! ! Une commande livrée dans une autre région ! ! Pas même une autre ville non ! ! Une autre région et on me dit qu ’ il faut faire une investigation qui va durer 15 jours pour comprendre pourquoi le colis est indiqué livré ! ! Ou est le bon sens ! ! !
---

Commande incomplète , on m'avertit au dernier moment , quand je demande un geste commercial , on me le refuse ... Pas correct , je suis cliente depuis les débuts ...
---

Suite à une commande le point relais a étais changer en me disant qu ’ il était fermé hors auchan est ouvert tout le temps suite à ça livraison retardée pour à la fin au bout de 1 mois me dire commande annulée sans raison Ayoub ne prend pas la peine de répondre merci je ne commanderai plus chez vous .
---

Service après vente déplorable . J'ai acheté une friteuse il y a un an qui ne fonctionne plus . J'ai vérifié la garantie qui est de 2 ans . Après avoir fait une demande de SAV il y a 10 jours . Je n'ai toujours aucun retour . Alors qu'ils s'engagent à répondre sous 48h.J'ai renvoyé un mail , il y 2 jours , toujours aucune réponse . Inacceptable .
---

Dans les temps de Noël , on commande sur le site deux luminaires pour SAM et salon . Quand nous avons voulu les brancher , il y avait court-circuit lorsque nous allumions les lumières . Nous avons alors pris contact par téléphone avec le SAV de Showroomprivé . Une dame très gentille et très agréable , nous a expliqué les démarches à suivre pour le retour gratuitement de ces produits . Comme le site n'était plus en mesure de nous les échanger , nous avons été remboursé rapidement sur notre compte .
---

Depuis quand il y a un délai de rétractation lorsqu ’ on veut fermer un compte et supprimer ses données ? Après une dernière commande décevante , j ’ ai décidé de quitter showroomprivé . J ’ ai reçu un appel aujourd ’ hui ou j ’ ai appris qu ’ il y avait un délai pour qu ’ il m ’ efface de leur banque de donner ! De plus il faut refaire la demande dans 14 jours ... C'est une blague ! ! ! !
---

Bonjour , J ’ ai commandé un salon de jardin ( 200 euros ) qui m ’ a été livré cassé . Après avoir contacté le SAV et de nombreux échanges de mails , on me propose un bon d ’ achat de 20 euros . Chose que je refuse et réitère ma demande de retour qui a été enfin accepté . La demande de retour s ’ est faite le 26 mars . Le transporteur est venu le chercher seulement le 17 avril . 15 jours après je n ’ avais toujours aucun remboursement . Cela fait plusieurs fois que je les contacts et je n ’ ai toujours pas été remboursé . C ’ est lamentable !
---

J ’ ai commander un article qui devait m ’ être livré à une date précise,3jours après la date indiquée , je téléphone au service client pour avoir des informations , ces derniers me transmet leurs excuses puis l ’ annonce du retard…sauf que le lendemain , je reçois un mail d ’ annulation de commande ! ! ! c ’ est lamentable ! ! ! Honteux ! ! ! !
---

bjrs malgre votre reponse ce qui est fait est malheureusement trop tard . comment peut on prendre la defense des agents de la poste .vous croyez tous meme pas que j ; ai garder le n° de commande depuis le temps ; il est trop tard pris pour etre appris . tous simplement de faire attention aux agent de la poste de laon dans l ; aisne 02000 . je ne changeraie aucunement d ; avis . decus je ne revendraie pas chez vous comme clientele.c ; est a vous de remettre en place le personnel de la poste et non pas accuser le client . simplement que j ; ai comme meme payer les produits .
---

Je devais recevoir mon colis le 7 mai , par ma grande surprise ces décaler le 11 mai et actuellement toujours rien ! ! Je déménage bientôt et impossible de modifier mon adresse ! Aucun message et aucune modification à était fait sur la date de la livraison
---

Colis perdu `` volé '' McQ , je passe commande pour 516,69€ de vêtements que du Mcq le 16/04 a ce jour je n'ai rien reçu , difficile de perdre le colis issue d'une seule vente , showroomprive le perd . Je contacte le service clients à 3 reprises avant d'avoir une réponse le colis a été retrouvé en parti ? ? et la on me bloque l'accès a mon compte je ne peux même plus suivre l'avancement de mon litige.Une seule option porter plainte contre ce site a arnaques qui ne respecte même pas les bon clients.A fuir
---

Commande passée il y a environ un mois avec une date fixe de livraison : aujourd ’ hui . Ce matin je me connecte et vois « livraison estimée le 18 mai » . J ’ ai toujours été élogieuse envers Showroom privé quant à la qualité des produits et la rapidité de livraison , mais je suis cette fois ici extrêmement déçue de ce changement de situation qui me met dans une situation inconfortable .
---

Client habituel ... La extrêmement dessus . J'ai commander une moto électrique repsol . La moto est arrivé sans batterie donc inutilisable . J'ai contacté le Sav qui mon promis le remboursement du prix de la batterie . Toujours rien . Dessus dessus dessus . C'est la vie
---

Encore une mauvaise expérience : 3 en un mois ! ! Troisième commande , cette fois-ci avec un article manquant.Nous allons faire une troisième réclamation mais nous connaissons d ’ ores et déjà la réponse du SAV . Dommage ! ! Nous commandons tres souvent chez les concurrents , sans aucun soucis . Là , le nombre récurrent de pb avec Showroom nous oblige à faire une croix ❌ rouge sur cette plateforme qui utilise des transporteurs malhonnêtes et qui ne donne aucune solution quand les livraisons ne sont pas honorées . Nous pensons porter plainte au tribunal administratif si les livraisons ne sont pas remboursées ...
---

L'an dernier j'avais pris une réservation de voyage . Covid oblige j'ai annulé . Ils n'ont jamais remboursé.Cette société ne respecte pas ces clients .Malgré les courriers de Que choisir Showroomprivé ne nous a jamais répondu donc je doute qu'aujourd'hui ils agissent.Malgré la réponse de Showroomprivé qui devait me contacter rapidement pour trouver une solution , ils ont toujours la même , ne pas me rembourser et continuer à me prendre pour une imbécile . A fuir définitivement
---

J'ai essayé de faire une commande le week-end , avec un code pour frais de livraison offert ( donné par le site ) , j ai fais une capture d'écran livraison offerte , mais au moment de payer , il rajoute les frais de livraison ... j ai appelé ce matin , le conseiller s embrouille tout seul , ne sais pas trop quoi me dire , heureusement que j ai une preuve ... bref pas sérieux , comme site , des usines à frics
---

j , ai commandé une grosse cafetière en mars 2021 livrable déjà au plus tard le 12/05/2021 , Ok mais hier déjà on me previent un retard jusqu ' a apres le 22/05/2021 Pas sérieux surtout que c'est payé depuis plus d'un mois et impossiuble d'annuler la commande cesont des plaisantins et c'est fini pour moi chez showrooprivé.com
---

Bonjour , déçue et pas contente , commande passée le 5/04 , premier mail il y a plus d ’ une semaine m ’ indiquant une nouvelle date de livraison au 3/05 , deux jours après un second avec pour excuse dysfonctionnement informatique , et ce matin que la livraison sera à nouveau programmer le 15/04 . ça commence à faire beaucoup , je paie une commande que je ne verrais jamais , j ’ avais repasser une commande hier mais je l ’ ai annuler ce matin vu comment ce passe cette commande actuellement . Je ne commanderai plus chez eux , Showroom a bien changer cela ne vaut plus celui qu ’ on a connu il y a quelques années .
---

j'ai fait une commande avec 3 outils électrique déjà ils me disent 1 mois pour être livrer même en chine c'est plus rapide et au bout d'un mois il ont rallonger de 3 semaines ... c'est une blague ! ! ! 2 mois d'attente pour une ponceuse électrique et 2 conneries super ...
---

Showroom est une société menteuse . Un remboursement intégral de la commande était prévu stipulé par mail , et j'ai été dans l'obligation de relancer le service client qui bien évidemment m'avait oublié pour finalement vouloir me rembourser qu'une partie de la commande . Et bien sûr on m'indique que j'ai mal compris cependant c'était un mail et donc écris noir sur blanc Donc aucune paroles aucun engagement tenu . Je déconseille fortement .
---

Très déçue par Shoowroomprivé , cela fait 2 fois en 3 mois que je reçois des articles défectueux ou non conformes . On m ' a dit que j'allais être remboursée des fdp mais je n'ai rien eu . J'ai appelé plusieurs fois mais évidemment je ne tombe jamais sur la même personnes impossible d'avoir les mêmes réponses . J'attends toujours l'appel de la personne qui s'est occupée de mon dossier .
---

J'ai réservé un voyage l'année passée.Départ impossible suite CovidCe jour je souhaite réservé un nouveau voyage et de ce fait utiliser mon avoir mais impossible car ce n'est pas le même tour opérateur ... Je demande donc un remboursement mais impossible.Service client incompétent
---

SERVICE CLIENT DE-PLO-RA-BLE , SUR PLUSIEURS APPELS , A CHAQUE CONSEILLER UNE REPONSE DIFFERENTE , 24H D'ATTENTE POUR AVOIR UNE REPONSE AU BOUT D'UNE ENIEME RELANCE QUI A FAIT QUE J'AI RATE LA VENTE
---

Renvoyé un colis d'un même magasin partenaire avec 2 articles à l'intérieur . Ils m'ont décompté 2 frais de retour soit 2x6,50€ . C'est purement scandaleux je ne commanderais plus jamais chez eux.Je reecris sur mon post pour dire que j'ai reçu un appel du service client ils me rembousent un frais de retour . Merci
---

Bonjour A déconseillé forcement Colis reçu sur mon espace et en vrai j'ai reçu le vent , deuxième fois j'ai commandé une montre homme à 1000 euros j'ai reçu une montre femme a 20 euros sur Amazon Service après vente nulle
---


In [ ]:
# Regroupement des topics
qualite_produit_topics = {3, 6, 18, 19, 23, 29}
livraison_topics = {5, 10, 24, 26, 27}
service_client_topics = {7, 8, 13, 14, 28}

df['label'] = np.nan

df.loc[df['topic_id'].isin(qualite_produit_topics), 'label'] = 0
df.loc[df['topic_id'].isin(livraison_topics), 'label'] = 1
df.loc[df['topic_id'].isin(service_client_topics), 'label'] = 2

df['label'] = df['label'].astype('Int64')  # int nullable
df['label'].value_counts(dropna=False)

label
<NA>    6191
0       4732
1       2374
2       1793
Name: count, dtype: Int64

Batches:   0%|          | 0/223 [00:00<?, ?it/s]

Batches:   0%|          | 0/56 [00:00<?, ?it/s]

LogisticRegression(class_weight='balanced', max_iter=2000)

              precision    recall  f1-score   support

         0.0      0.953     0.864     0.906       946
         1.0      0.796     0.819     0.807       475
         2.0      0.756     0.914     0.827       359

    accuracy                          0.862      1780
   macro avg      0.835     0.865     0.847      1780
weighted avg      0.871     0.862     0.864      1780

Classe prédite  0.0  1.0  2.0
Classe réelle
0               817   76   53
1                33  389   53
2                 7   24  328

,text,label_true,label_pred,correct
1,j'ai du leurs écrire pendant 2 mois pour me faire rembourser et en plis je n'ai reçu que la moitié . je n'ai jamais reçu ma commande et le service client vous prends pour des… je ne sais même pas s'il s'agit de réels personnes . je ne commanderai plus jamais .,0,2.0,False
3,sur 5 commande jai eu 3 problèmes soit produit manquant soit apres 2 mois d'attente 2 jours avant la livraison ma commande a etait annulé ... ou reception d'un autre article qui n'était pas le mien ... j'hésite a recommander ...,0,1.0,False
6,erreur de livraison . pieces manquantes . colis incomplet .,0,1.0,False
8,j ’ attends depuis des semaines le remboursement de 2 articles retournés ....,0,2.0,False
21,"commande livrée très vite ce qui est très agréable , car bien souvent les délais sont trop longs",0,1.0,False
39,"une catastrophe , le colis est arrivé ouvert et en mauvais état . les produits avaient fuit et étaient a même le carton . une honte .",1,0.0,False
40,"des années que je commande sur veepee et toujours au top . quand je commande chez eux je n'ai jamais été déçu , ils ne se trompent pas dans l'article comme shorommprive trois fois ils se sont trompé de commande . je reçois la plupart toujours à l'avance mais rarement en retard . merci",0,2.0,False
41,une commande passée il y a 4mois . je viens tout juste de recevoir un mail pour me dire que je vais être remboursé et qu ’ ils n ’ allaient pas me livrer ... un service déplorable . je déconseille fortement .,1,2.0,False
44,"commande effectuée le 17 décembre , soit disant expédiée le 20 . j ’ ai contacté le service client par e-mail et j ’ ai eu la chance d ’ obtenir une réponse type « ils effectuent des recherches et me tiennent au courant » . aujourd ’ hui , 2 janvier , aucune nouvelle de mon colis . mon compte en banque a bien sûr été débité depuis longtemps . je extrêmement déçue par l ’ évolution de ce site de vente en ligne .",1,2.0,False
50,"retard sur la livraison mais assez satisfaite sur le produit . seul regret , j ’ aurai du commander taille 54 au lieu de 52",0,1.0,False
52,je ne peux me permettre de juger le service client car je n ’ ai pas encore eu besoin d ’ avoir à faire avec eux cordialement,0,2.0,False
65,livraison avant la date prévue . petite déception sur le tableau qui n ' a pas autant de touches de doré que sur l'image du site .,0,1.0,False
67,"boite à pain cassé dans le colis pas assez protégé dommage pour moi car elle me plaisait beaucoup et le retour est a ma charge alors que je n ' y suis pour rien ? je ne comprends pas qu'il n ' y es pas un échange , ?",1,0.0,False
70,"j'ai fait 4 retours , pas de remboursement . un article n ' a pas été livré , pas de remboursement non plus ! ils ne remboursent plus rien . a fuir ! ! !",0,2.0,False
75,"incompétence et mauvaise foi ! showroomprive ne respecte pas les termes du contrat infinity ! certains articles , alors qu'ils sont désignés comme faisant partie d ela livraison gratuite n'en bénéficient pas , selon l'humeur de showroomprivé ! je déconseille fortement ce site , je n'ai eu que des problèmes !",0,2.0,False
90,"voilà depuis ma commande du 16 décembre , j'attends de recevoir un reconditionné d'une valeur de 659€ frais de port compris , qui est soit disant en traitement dans leur plateforme logistique et donc prêt à être envoyé . avec une estimation de livraison entre le 27 et 29 décembre . on est le 7 janvier toujours rien reçu , pas de réponse à mes mails , du coup je souhaite annuler la commande mais impossible sur le site . donc je vais les harceler au pour récupérer mon argent ce qui est déjà de trop .je ne compte pas en rester là mais je vais faire tout ce qui est possibles pour faire fermer cette boîte juridiquement parlant et quel ne puisse plus jamais nuire au consommateur .",1,2.0,False
92,"3 commandes passées , 3 commandes annulées à peine une semaine avant ladite livraison.pas de raison invoquée , je supprime l ’ application et commande désormais sur d ’ autres sites plus fiables .",0,1.0,False
94,"je suis tres mecontent de ce site j ’ ai commandé un lit nightandmore en 200x200 ( et matelas ) vu la taille , il y avait deux lors de la livraison ce jour , jai bien recu les deux et le matelas mais a ma grande surprise seulement 4pieds au lieu de 8 . j ’ ai donc refuser la commande . sauf que comme j ’ avais pris mes dispositions pour mon anciens lit . je ne l ’ ai plus . je me retrouver donc avec rien pour dormir . la solution de votre groupe de m e r d e , repasser commande lol mais surtout aucune solution j ’ attend donc d ’ etre recontacter dans les plus brefs delai afin que vous me trouviez une solution car meme si je recommande un lit qui me convienne , les delai de livraison sont tels que je vais rester 1 , 2 voir plusieurs mois sans lit . je vous demande donc de prendre en consideration cela et de me recontacter avec une vrai solution",2,0.0,False
112,"je donne une étoile car je ne peux pas mettre moins . jusqu ' à présent je commandais pas mal sur vente-privé malgré les frais de livraison de 6,50€ sur quasiment toutes les ventes qui freinent l'achat ( heureusement pour mon compte en banque ) . j'ai fais une commande début juillet , la livraison était prévue entre le 31/07/2017 et le 05/08/2017 . a ce jour m ' a commande n ' a toujours pas été expédié , je n'ai eu aucune explication . j'ai essayé de les contacter à plusieurs reprises , sans nouvelle de leur part et le pire c'est que je peux même pas annuler ma commander car le fournisseur à déjà expédié ma commande et se trouve actuellement dans l'entrepôt de vente-privée . qu'est ce qui les empêche donc de me la faire parvenir ? en conclusion je ne recommanderai absolument pas ce site de vente en ligne.suite de l'épisode : après avoir posté ce commentaire ils m'ont informé que ma commande ne sera pas livré . j'ai donc été remboursé . 1 mois d'attente pour avoir un produit qui au final n'arrivera jamais .",1,2.0,False
113,il manque 90 % de ma commande et je n'ai pas d'infos sur le fait de la recevoir ou non en totalité un jour .,0,1.0,False